'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { supabaseBrowser } from '../../../../lib/supabase-browser';
import { Badge, Button, Card, SectionHeading } from '../../../../components/ui';

type Offer={id:string;publication_id:string;project_id:string;version_no:number;status:string;validity:string;created_at:string;submitted_at:string|null;withdrawn_at:string|null;expires_at:string;publication_title:string;publication_status:string;submission_deadline:string|null;lot_count:number;total_millimes:number;selected_count:number;not_selected_count:number};
const labels:Record<string,string>={draft:'Brouillon',submitted:'Soumise',withdrawn:'Retirée',expired:'Expirée',superseded:'Remplacée'};
const tones:Record<string,'neutral'|'teal'|'clay'|'red'>={draft:'clay',submitted:'teal',withdrawn:'neutral',expired:'red',superseded:'neutral'};
const money=(value:number)=>new Intl.NumberFormat('fr-TN',{style:'currency',currency:'TND',maximumFractionDigits:3}).format(Number(value)/1000);

export default function MyOffers(){
  const [offers,setOffers]=useState<Offer[]>([]);const [filter,setFilter]=useState('all');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function load(){setLoading(true);const {data,error:rpcError}=await supabaseBrowser().rpc('my_bid_summaries');if(rpcError)setError('Impossible de charger vos offres.');else setOffers((data??[]) as Offer[]);setLoading(false)}
  useEffect(()=>{void load()},[]);
  const rows=useMemo(()=>filter==='all'?offers:offers.filter(o=>o.status===filter),[offers,filter]);
  async function withdraw(offer:Offer){if(!window.confirm(`Retirer définitivement la version ${offer.version_no} de cette offre ? Son contenu restera dans votre historique.`))return;setBusy(offer.id);setError('');setMessage('');const {data}=await supabaseBrowser().auth.getSession();if(!data.session){setError('Session expirée.');setBusy('');return}const response=await fetch('/api/bids/withdraw',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({version_id:offer.id})});const body=await response.json().catch(()=>({}));if(!response.ok)setError(body.error||'Le retrait de cette offre a été refusé.');else{setMessage('Offre retirée. Son contenu reste consultable dans votre historique.');await load()}setBusy('')}
  if(loading)return <p>Chargement de vos offres…</p>;
  return <section className="space-y-6"><SectionHeading eyebrow="Espace artisan" title="Mes offres" description="Une vue globale de vos brouillons, offres soumises, résultats et retraits." action={<Link href="/app/artisan" className="text-sm font-semibold text-teal">Voir les DAO disponibles</Link>}/><Card><label className="text-sm font-semibold">État<select className="ml-3 rounded-xl border border-black/10 bg-white px-3 py-2" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Toutes</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></Card>{error&&<p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="rounded-xl bg-teal/10 px-4 py-3 text-sm text-teal">{message}</p>}{rows.length===0?<Card className="border-dashed text-center"><h2 className="font-bold">Aucune offre</h2><p className="mt-2 text-sm text-black/55">Vos brouillons et offres soumises apparaîtront ici.</p><Link href="/app/artisan" className="mt-4 inline-flex font-semibold text-teal">Découvrir les DAO</Link></Card>:<div className="space-y-3">{rows.map(offer=><Card key={offer.id}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><Badge tone={tones[offer.status]??'neutral'}>{labels[offer.status]??offer.status}</Badge><span className="text-xs text-black/45">Version {offer.version_no}</span>{offer.selected_count>0&&<Badge tone="teal">{offer.selected_count} lot{offer.selected_count>1?'s':''} retenu{offer.selected_count>1?'s':''}</Badge>}{offer.not_selected_count>0&&<Badge>{offer.not_selected_count} non retenu{offer.not_selected_count>1?'s':''}</Badge>}</div><h2 className="mt-3 text-lg font-bold">{offer.publication_title}</h2><p className="mt-2 text-sm text-black/55">{offer.lot_count} lot{offer.lot_count>1?'s':''} · {money(offer.total_millimes)}{offer.submitted_at?` · envoyée le ${new Date(offer.submitted_at).toLocaleDateString('fr-TN')}`:''}{offer.withdrawn_at?` · retirée le ${new Date(offer.withdrawn_at).toLocaleDateString('fr-TN')}`:''}</p></div><div className="flex flex-wrap gap-2"><Link href={`/app/artisan/publications/${offer.publication_id}`} className="inline-flex min-h-10 items-center rounded-xl border border-black/10 px-4 py-2 text-sm font-semibold">Voir le DAO</Link>{offer.status==='submitted'&&offer.selected_count===0&&<Button className="bg-white text-red-700 ring-1 ring-red-200 hover:bg-red-50" disabled={busy===offer.id} onClick={()=>void withdraw(offer)}>{busy===offer.id?'Retrait…':'Retirer l’offre'}</Button>}</div></div></Card>)}</div>}</section>
}
