'use client';
import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Badge, Button, Card, Input } from '../ui';
import { statusLabel } from '../../lib/utils';
import { readBackoffice, commandBackoffice, actionLabels, type BackofficeResult } from '../../lib/backoffice';
const roleLabels: Record<string,string> = { client:'Client',contractor:'Artisan / Entreprise',dao_reviewer:'Gestionnaire',dao_admin:'Admin' };
const titles: Record<string,string> = { professionals:'Professionnels',clients:'Clients',users:'Utilisateurs & rôles',history:'Historique' };
export default function Directory({ view }: { view: 'professionals'|'clients'|'users'|'history' }) {
  const [result,setResult]=useState<BackofficeResult|null>(null),[filters,setFilters]=useState<Record<string,string>>({q:'',offset:'0'}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  const [selected,setSelected]=useState<any>(null),[action,setAction]=useState<{action:string;input:any;label:string;reason?:boolean}|null>(null),[reason,setReason]=useState('');
  const [invite,setInvite]=useState({email:'',display_name:'',role:'dao_reviewer'}),[inviteKey,setInviteKey]=useState('');
  const generation=useRef(0);
  const load=useCallback(async()=>{const current=++generation.current;setLoading(true);setError('');try{const next=await readBackoffice(view,filters);if(current===generation.current)setResult(next);}catch(e:any){if(current===generation.current){setError(e.message);setResult(null);}}finally{if(current===generation.current)setLoading(false);}},[view,filters]);
  useEffect(()=>{if(view==='history'){const params=new URLSearchParams(window.location.search);const supported=['project_id','actor_id','client_id','contractor_id','lot_id','publication_id','q'];setFilters(f=>({...f,...Object.fromEntries(supported.filter(k=>params.has(k)).map(k=>[k,params.get(k)!]))}));}},[view]);
  useEffect(()=>{void load();},[load]);
  const change=(key:string,value:string)=>setFilters(f=>({...f,[key]:value,offset:'0'}));
  function prepare(action:string,input:any,label:string,needsReason=false){setReason('');setAction({action,input,label,reason:needsReason});}
  async function execute(){if(!action)return;setSaving(true);setError('');try{await commandBackoffice(action.action,{...action.input,...(reason.trim()?{reason:reason.trim()}:{})});setMessage('Modification enregistrée.');setAction(null);setSelected(null);await load();}catch(e:any){setError(e.message);}finally{setSaving(false);}}
  async function inviteStaff(e:FormEvent){e.preventDefault();setSaving(true);setError('');const key=inviteKey||crypto.randomUUID();setInviteKey(key);try{await commandBackoffice('invite_staff',invite,key);setMessage('Compte staff invité. Le destinataire définit son mot de passe depuis l’email Supabase.');setInvite({email:'',display_name:'',role:'dao_reviewer'});setInviteKey('');await load();}catch(e:any){setError(e.message);}finally{setSaving(false);}}
  return <section className="mx-auto max-w-6xl space-y-5"><div><p className="text-sm font-semibold text-teal">Espace DAO</p><h1 className="mt-1 text-3xl font-bold">{titles[view]}</h1></div>
    <form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void load();}}><label className="min-w-48 flex-1 text-sm">Recherche<Input aria-label={`Rechercher ${titles[view].toLowerCase()}`} value={filters.q} onChange={e=>change('q',e.target.value)} placeholder="Nom, email ou action" /></label>{view!=='history'&&<label className="text-sm">État<select className="mt-1 rounded-xl border p-3" value={filters.status||''} onChange={e=>change('status',e.target.value)}><option value="">Tous</option>{(view==='professionals'?['pending','verified','rejected','suspended']:['active','suspended']).map(s=><option key={s} value={s}>{statusLabel[s]||({active:'Actif',verified:'Vérifié',pending:'En attente'} as Record<string,string>)[s]||s}</option>)}</select></label>}{view==='history'&&<><label className="text-sm">Depuis<Input type="date" value={filters.from||''} onChange={e=>change('from',e.target.value)} /></label><label className="text-sm">Jusqu’au<Input type="date" value={filters.to||''} onChange={e=>change('to',e.target.value)} /></label><label className="text-sm">Action<select className="mt-1 max-w-64 rounded-xl border p-3" value={filters.action||''} onChange={e=>change('action',e.target.value)}><option value="">Toutes</option>{Object.entries(actionLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><details className="w-full"><summary className="cursor-pointer text-sm">Filtres du dossier</summary><div className="mt-3 grid gap-3 sm:grid-cols-3">{[['actor_id','Auteur'],['client_id','Client'],['contractor_id','Professionnel'],['project_id','Chantier'],['lot_id','Lot'],['publication_id','Publication']].map(([key,label])=><label key={key} className="text-sm">{label}<Input placeholder="Identifiant du dossier" value={filters[key]||''} onChange={e=>change(key,e.target.value)} /></label>)}</div></details></>}</form>
    {error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-teal">{message}</p>}{loading&&<p>Chargement…</p>}
    {result&&<><div className="grid gap-3 md:grid-cols-2">{result.rows.map((row:any)=>view==='history'?<Card key={row.id}><h2 className="font-semibold">{actionLabels[row.action]||row.action}</h2><p className="mt-2 text-sm">{row.actor_name||'Auteur historique'} · {new Date(row.created_at).toLocaleString('fr-TN')}</p><p className="mt-2 text-sm font-semibold">{row.subject_name}</p><p className="text-sm">{row.project_title}{row.client_name&&` · Client : ${row.client_name}`}</p>{row.metadata.reason&&<p className="mt-2 text-sm">Motif : {row.metadata.reason}</p>}{row.metadata.acting_for_client&&<Badge>Pour le compte du client</Badge>}<details className="mt-3 text-xs"><summary>Références de l’événement</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap">{JSON.stringify(row.metadata,null,2)}</pre></details></Card>:<button type="button" key={row.id} className="text-left" onClick={()=>setSelected(row)}><Card className="h-full hover:border-teal"><h2 className="font-semibold">{row.business_name||row.display_name}</h2><p className="mt-2 break-all text-sm text-black/60">{row.email||'Email non renseigné'}</p><div className="mt-3 flex flex-wrap gap-2"><Badge>{({pending:'En attente',verified:'Vérifié',rejected:'Refusé',active:'Actif',suspended:'Suspendu'} as Record<string,string>)[row.verification_status||row.account_status]||row.account_status}</Badge>{row.roles?.map((r:string)=><Badge key={r}>{roleLabels[r]}</Badge>)}</div><span className="mt-3 block text-sm font-semibold text-teal">Ouvrir le dossier →</span></Card></button>)}</div>{result.rows.length===0&&<Card>Aucun résultat.</Card>}<div className="flex justify-between gap-3"><Button disabled={Number(filters.offset)===0||loading} onClick={()=>setFilters(f=>({...f,offset:String(Math.max(0,Number(f.offset)-100))}))}>Précédent</Button><Button disabled={result.rows.length<100||loading} onClick={()=>setFilters(f=>({...f,offset:String(Number(f.offset)+100)}))}>Suivant</Button></div></>}
    {view==='users'&&result?.admin&&<Card><h2 className="text-xl font-semibold">Inviter un membre staff</h2><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={inviteStaff}><label>Nom<Input required maxLength={200} value={invite.display_name} onChange={e=>{setInvite({...invite,display_name:e.target.value});setInviteKey('');}} /></label><label>Email<Input required type="email" value={invite.email} onChange={e=>{setInvite({...invite,email:e.target.value});setInviteKey('');}} /></label><label>Rôle<select className="mt-1 w-full rounded-xl border p-3" value={invite.role} onChange={e=>{setInvite({...invite,role:e.target.value});setInviteKey('');}}><option value="dao_reviewer">Gestionnaire</option><option value="dao_admin">Admin</option></select></label><Button disabled={saving}>{saving?'Invitation…':'Envoyer l’invitation'}</Button></form></Card>}
    {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-ink/40 p-4"><Card className="mx-auto my-5 max-w-2xl" role="dialog" aria-modal="true" aria-label="Dossier du compte"><div className="flex justify-between gap-4"><h2 className="text-2xl font-bold">{selected.business_name||selected.display_name}</h2><Button onClick={()=>setSelected(null)}>Fermer</Button></div><p className="mt-3 break-all">{selected.email}</p><p className="mt-2 text-sm">Compte {selected.account_status} {view==='users'&&` · Email ${selected.email_confirmed?'confirmé':'à confirmer'}`}</p>{selected.contacts?.map((c:any)=><p key={c.id} className="mt-2 text-sm">{c.phone_e164} {c.contact_email}</p>)}{selected.trades?.map((t:any)=><Badge key={t.trade_id}>{t.name}</Badge>)}{selected.invitations?.map((i:any)=><p key={i.id} className="mt-3 text-sm">Invitation {i.expected_role==='client'?'Client':'Artisan / Entreprise'} · {statusLabel[i.status]||i.status} · {new Date(i.expires_at).toLocaleDateString('fr-TN')}</p>)}<Link className="mt-4 block text-sm font-semibold text-teal" href={`/app/dao/history?${view==='professionals'?'contractor_id':view==='clients'?'client_id':'q'}=${selected.id}`}>Historique du dossier →</Link>{selected.projects?.map((p:any)=><Link key={p.id} className="mt-3 block text-teal" href={`/app/dao/projects/${p.id}`}>{p.title} · {p.status}</Link>)}
      {view==='professionals'&&<><p className="mt-3">Vérification : {selected.verification_status} · Identité publique : {selected.public_identity_status}</p><div className="mt-4 flex flex-wrap gap-3"><Button disabled={selected.verification_status==='suspended'} onClick={()=>prepare('professional',{contractor_id:selected.id,decision:'verify'},'Vérifier ce professionnel')}>Vérifier</Button><Button disabled={selected.verification_status==='suspended'} onClick={()=>prepare('professional',{contractor_id:selected.id,decision:'reject'},'Refuser ce professionnel',true)}>Refuser</Button>{result?.admin&&<><Button onClick={()=>prepare('professional',{contractor_id:selected.id,decision:selected.verification_status==='suspended'?'reactivate':'suspend'},selected.verification_status==='suspended'?'Réactiver le professionnel':'Suspendre le professionnel',selected.verification_status!=='suspended')}>{selected.verification_status==='suspended'?'Réactiver':'Suspendre'}</Button><Button onClick={()=>prepare('professional',{contractor_id:selected.id,decision:selected.public_identity_status==='approved'?'hide_identity':'approve_identity'},'Modifier la visibilité de l’identité')}>{selected.public_identity_status==='approved'?'Masquer l’identité':'Approuver l’identité'}</Button></>}</div></>}
      {view==='users'&&result?.admin&&<div className="mt-5 space-y-3"><h3 className="font-semibold">Rôles cumulables</h3>{Object.entries(roleLabels).map(([r,label])=><label key={r} className="flex items-center gap-3"><input type="checkbox" checked={selected.roles.includes(r)} disabled={saving} onChange={e=>prepare('role',{user_id:selected.id,role:r,enabled:e.target.checked},`${e.target.checked?'Ajouter':'Retirer'} le rôle ${label}`)} />{label}</label>)}</div>}
      {result?.admin&&view!=='professionals'&&<Button className="mt-5" onClick={()=>prepare('account',{user_id:selected.id,status:selected.account_status==='suspended'?'active':'suspended'},selected.account_status==='suspended'?'Réactiver le compte':'Suspendre le compte',selected.account_status!=='suspended')}>{selected.account_status==='suspended'?'Réactiver':'Suspendre le compte'}</Button>}
    </Card></div>}
    {action&&<div className="fixed inset-0 z-[60] overflow-auto bg-ink/50 p-5"><Card role="dialog" aria-modal="true" aria-label="Confirmer la modification" className="mx-auto my-20 max-w-lg"><h2 className="text-xl font-bold">{action.label}</h2><p className="mt-3 text-sm">L’action et son auteur seront conservés dans l’historique.</p>{action.reason&&<label className="mt-4 block">Motif obligatoire<textarea className="mt-2 w-full rounded-xl border p-3" required value={reason} onChange={e=>setReason(e.target.value)} /></label>}{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}<div className="mt-5 flex gap-3"><Button disabled={saving||(action.reason&&!reason.trim())} onClick={()=>void execute()}>Confirmer</Button><Button disabled={saving} onClick={()=>setAction(null)}>Annuler</Button></div></Card></div>}
  </section>;
}
