'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Badge, Card, Input, Button } from '../ui';
import { statusLabel } from '../../lib/utils';
import { readBackoffice, type BackofficeResult } from '../../lib/backoffice';
export default function Projects(){
  const [filters,setFilters]=useState({q:'',status:'',mine:'false',offset:'0'}),[result,setResult]=useState<BackofficeResult|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;setError('');void readBackoffice('projects',filters).then(r=>{if(active)setResult(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[filters]);
  return <section className="space-y-5"><h1 className="text-3xl font-bold">Chantiers</h1><div className="flex flex-wrap gap-3"><Input className="max-w-md" aria-label="Rechercher un chantier" placeholder="Titre ou client" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value,offset:'0'})} /><select aria-label="État du chantier" className="rounded-xl border p-3" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value,offset:'0'})}><option value="">Tous les états</option>{['draft','client_review','dao_review','approved','rejected'].map(s=><option key={s} value={s}>{statusLabel[s]||s}</option>)}</select><label className="flex items-center gap-2"><input type="checkbox" checked={filters.mine==='true'} onChange={e=>setFilters({...filters,mine:String(e.target.checked),offset:'0'})} />Mes revues</label></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{!result&&!error&&<p>Chargement…</p>}<div className="grid gap-3 md:grid-cols-2">{result?.rows.map((p:any)=><Link key={p.id} href={`/app/dao/projects/${p.id}`}><Card className="h-full hover:border-teal"><h2 className="text-lg font-bold">{p.version.title}</h2><p className="mt-2 text-sm">Client : {p.client_name||'Non affecté'}</p><p className="mt-2 text-sm">Pris en charge par : {p.reviewer_name||'À prendre en charge'}</p><div className="mt-3 flex gap-2"><Badge>{statusLabel[p.version.status]||p.version.status}</Badge><Badge>Version {p.version.version_no}</Badge></div><p className="mt-3 text-sm text-teal">{p.can_manage?'Ouvrir et gérer le dossier':'Ouvrir en lecture seule'} →</p></Card></Link>)}</div>{result?.rows.length===0&&<Card>Aucun chantier.</Card>}<div className="flex justify-between"><Button disabled={filters.offset==='0'} onClick={()=>setFilters({...filters,offset:String(Math.max(0,Number(filters.offset)-100))})}>Précédent</Button><Button disabled={!result||result.rows.length<100} onClick={()=>setFilters({...filters,offset:String(Number(filters.offset)+100)})}>Suivant</Button></div></section>;
}
