'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Badge, Card, Input, Button } from '../ui';
import { effectiveProjectStatus, statusLabel } from '../../lib/utils';
import { readAllBackoffice, type BackofficeResult } from '../../lib/backoffice';
export default function Projects(){
  const [filters,setFilters]=useState({q:'',status:'',mine:'false',offset:'0'}),[result,setResult]=useState<BackofficeResult|null>(null),[error,setError]=useState(''),[readyOnly,setReadyOnly]=useState(false),[initialized,setInitialized]=useState(false),[loading,setLoading]=useState(true);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setFilters(f=>({...f,status:params.get('status')||'',q:params.get('q')||'',mine:params.get('mine')==='true'?'true':'false'}));setReadyOnly(params.get('publishable')==='true');setInitialized(true);},[]);
  useEffect(()=>{if(!initialized)return;let active=true;setLoading(true);setError('');setResult(null);void readAllBackoffice('projects',{q:filters.q,mine:filters.mine}).then(rows=>{if(active)setResult({rows:rows.map((p:any)=>({...p,version:{...p.version,status:effectiveProjectStatus(p.status,p.version.status)}})).filter((p:any)=>(!filters.status||p.version.status===filters.status)&&(!readyOnly||(p.version.status==='approved'&&Number(p.publishable_lots)>0))),admin:false,actor_id:'',offset:0,limit:100});}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[filters.q,filters.status,filters.mine,readyOnly,initialized]);
  const visible=result?.rows.slice(Number(filters.offset),Number(filters.offset)+100);
  return <section className="space-y-5"><h1 className="text-3xl font-bold">Chantiers</h1><div className="flex flex-wrap gap-3"><Input className="max-w-md" aria-label="Rechercher un chantier" placeholder="Titre ou client" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value,offset:'0'})} /><label className="flex items-center gap-2"><input type="checkbox" checked={readyOnly} onChange={e=>{setReadyOnly(e.target.checked);setFilters({...filters,offset:'0'});}} />Prêts à publier uniquement</label><select aria-label="État du chantier" className="rounded-xl border p-3" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value,offset:'0'})}><option value="">Tous les états</option>{['draft','client_review','dao_review','approved','rejected','archived'].map(s=><option key={s} value={s}>{statusLabel[s]||s}</option>)}</select><label className="flex items-center gap-2"><input type="checkbox" checked={filters.mine==='true'} onChange={e=>setFilters({...filters,mine:String(e.target.checked),offset:'0'})} />Mes revues</label></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading&&<p>Chargement…</p>}<div className="grid gap-3 md:grid-cols-2">{visible?.map((p:any)=><Link key={p.id} href={`/app/dao/projects/${p.id}`}><Card className="h-full hover:border-teal"><h2 className="text-lg font-bold">{p.version.title}</h2><p className="mt-2 text-sm">Client : {p.client_name||'Non affecté'}</p><p className="mt-2 text-sm">Pris en charge par : {p.reviewer_name||'À prendre en charge'}</p><div className="mt-3 flex gap-2"><Badge>{statusLabel[p.version.status]||p.version.status}</Badge><Badge>Version {p.version.version_no}</Badge></div><p className="mt-3 text-sm text-teal">{p.can_manage?'Ouvrir et gérer le dossier':'Ouvrir en lecture seule'} →</p></Card></Link>)}</div>{result?.rows.length===0&&<Card>Aucun chantier.</Card>}<div className="flex justify-between"><Button disabled={loading||filters.offset==='0'} onClick={()=>setFilters({...filters,offset:String(Math.max(0,Number(filters.offset)-100))})}>Précédent</Button><Button disabled={loading||!result||Number(filters.offset)+100>=result.rows.length} onClick={()=>setFilters({...filters,offset:String(Number(filters.offset)+100)})}>Suivant</Button></div></section>;
}
