'use client';
import { useState } from 'react';
import { Button, Card } from '../ui';
import { commandBackoffice, withdrawalReasons } from '../../lib/backoffice';
export default function WithdrawLot({lot,onWithdraw}:{lot:{id:string;safe_title:string};onWithdraw:()=>void}){
  const [open,setOpen]=useState(false),[reason,setReason]=useState(''),[comment,setComment]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function withdraw(){setSaving(true);setError('');try{await commandBackoffice('withdraw_publication_lot',{publication_request_id:lot.id,reason,comment});setOpen(false);onWithdraw();}catch(e:any){setError(e.message);}finally{setSaving(false);}}
  return <><Button className="mt-3 bg-white text-red-700 ring-1 ring-red-200" onClick={()=>setOpen(true)}>Retirer de la publication</Button>{open&&<div className="fixed inset-0 z-50 overflow-auto bg-ink/40 p-4"><Card className="mx-auto my-16 max-w-lg" role="dialog" aria-modal="true" aria-label="Retirer un lot"><h2 className="text-xl font-bold">Retirer {lot.safe_title}</h2><p className="mt-3 text-sm">Les nouvelles offres seront bloquées immédiatement. Les offres déjà soumises et cette publication resteront dans l’historique. Les autres lots restent actifs.</p><label className="mt-4 block text-sm">Motif<select aria-label="Motif" required className="mt-2 w-full rounded-xl border p-3" value={reason} onChange={e=>setReason(e.target.value)}><option value="">Choisir un motif</option>{Object.entries(withdrawalReasons).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="mt-3 block text-sm">Commentaire{reason==='other'?' obligatoire':''}<textarea aria-label={reason==='other'?'Commentaire obligatoire':'Commentaire'} className="mt-2 w-full rounded-xl border p-3" value={comment} onChange={e=>setComment(e.target.value)} /></label>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}<div className="mt-4 flex gap-3"><Button disabled={saving||!reason||(reason==='other'&&!comment.trim())} onClick={()=>void withdraw()}>Confirmer le retrait</Button><Button disabled={saving} onClick={()=>setOpen(false)}>Annuler</Button></div></Card></div>}</>;
}
