'use client';
import {useEffect,useState} from 'react';
import {supabaseBrowser} from '../../../../lib/supabase-browser';
import {Badge,Button,Card} from '../../../../components/ui';
export default function DaoReview(){const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');
 async function load(){const {data}=await supabaseBrowser().from('project_versions').select('id,project_id,title,description,status,version_no').in('status',['client_review','dao_review']).order('created_at',{ascending:true});setRows(data??[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function decide(row:any,approve:boolean){setMessage('');const {data}=await supabaseBrowser().auth.getSession();if(!data.session){setMessage('Session expirée.');return}const r=await fetch('/api/dao/review/decision',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({project_id:row.project_id,approve,comment:approve?'Validé par DAO':'À corriger par le client'})});const b=await r.json();if(!r.ok){setMessage(b.error||'Action refusée.');return}setMessage(approve?'Étape de revue validée.':'Projet refusé.');await load()}
 if(loading)return <p>Chargement…</p>;return <section className="mx-auto max-w-4xl space-y-6"><div><p className="text-sm font-semibold text-teal">Espace DAO</p><h1 className="mt-1 text-3xl font-bold">Revues en attente</h1></div>{message&&<p role="status" className="text-sm text-teal">{message}</p>}{rows.length===0?<Card>Aucune revue en attente.</Card>:rows.map(row=><Card key={row.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">{row.title}</h2><p className="mt-1 text-sm text-black/55">{row.description}</p></div><Badge>{row.status}</Badge></div><div className="mt-4 flex gap-2"><Button onClick={()=>void decide(row,true)}>{row.status==='client_review'?'Passer en revue DAO':'Approuver'}</Button><Button className="bg-white text-red-600" onClick={()=>void decide(row,false)}>Refuser</Button></div></Card>)}</section>}
