'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, MapPin, Ruler, Wallet } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { supabaseBrowser } from '../../../../lib/supabase-browser';
import { Badge, Button, Card, Input } from '../../../../components/ui';

type Territory = { id: string; name_fr: string; governorate_id?: string; delegation_id?: string };
const moneyToMillimes = (value: string) => value ? Math.round(Number(value) * 1000) : null;
const types = { construction: 'Construction', renovation: 'Rénovation', repair: 'Réparation', extension: 'Extension', other: 'Autre' };

export default function NewProject() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [form, setForm] = useState({ title: '', description: '', type: 'renovation', surface: '', budget: '', date: '', endDate: '', governorate: '', delegation: '', locality: '' });
  const [governorates, setGovernorates] = useState<Territory[]>([]); const [delegations, setDelegations] = useState<Territory[]>([]); const [localities, setLocalities] = useState<Territory[]>([]);
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value, ...(key === 'governorate' ? { delegation: '', locality: '' } : {}), ...(key === 'delegation' ? { locality: '' } : {}) }));
  useEffect(() => { void (async () => { const { data } = await supabaseBrowser().from('governorates').select('id,name_fr').order('name_fr'); setGovernorates(data ?? []); })(); }, []);
  useEffect(() => { if (!form.governorate) { setDelegations([]); return; } void (async () => { const { data } = await supabaseBrowser().from('delegations').select('id,name_fr,governorate_id').eq('governorate_id', form.governorate).order('name_fr'); setDelegations(data ?? []); })(); }, [form.governorate]);
  useEffect(() => { if (!form.delegation) { setLocalities([]); return; } void (async () => { const { data } = await supabaseBrowser().from('localities').select('id,name_fr,delegation_id').eq('delegation_id', form.delegation).order('name_fr'); setLocalities(data ?? []); })(); }, [form.delegation]);
  const selected = useMemo(() => ({ governorate: governorates.find(item => item.id === form.governorate)?.name_fr, delegation: delegations.find(item => item.id === form.delegation)?.name_fr, locality: localities.find(item => item.id === form.locality)?.name_fr }), [delegations, form.delegation, form.governorate, form.locality, governorates, localities]);

  function validate(nextStep: number) { setError(''); if (nextStep >= 2 && !form.title.trim()) { setError('Ajoutez un titre pour votre projet.'); return false; } if (nextStep >= 3 && !form.governorate) { setError('Choisissez au moins un gouvernorat.'); return false; } if (form.date && form.endDate && form.endDate < form.date) { setError('La date de fin doit être postérieure ou égale à la date de début.'); return false; } return true; }
  function next(event: React.MouseEvent<HTMLButtonElement>) { event.preventDefault(); if (validate(step + 1)) setStep(value => Math.min(4, value + 1)); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!validate(4)) return; setSaving(true); setError(''); const { data } = await supabaseBrowser().auth.getSession(); if (!data.session) { router.push('/auth/login'); return; } const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${data.session.access_token}` }; const created = await fetch('/api/projects', { method: 'POST', headers, body: JSON.stringify({ project_type: form.type, surface_m2: form.surface ? Number(form.surface) : null, desired_start_date: form.date || null, desired_end_date: form.endDate || null, indicative_budget_millimes: moneyToMillimes(form.budget), governorate_id: form.governorate, delegation_id: form.delegation || null, locality_id: form.locality || null }) }); const payload = await created.json().catch(() => ({})); if (!created.ok || !payload.data?.id) { setError(payload.error || 'Impossible de créer le projet.'); setSaving(false); return; } const updated = await fetch('/api/projects', { method: 'PATCH', headers, body: JSON.stringify({ project_id: payload.data.id, title: form.title, description: form.description, project_type: form.type, surface_m2: form.surface ? Number(form.surface) : null, desired_start_date: form.date || null, desired_end_date: form.endDate || null, indicative_budget_millimes: moneyToMillimes(form.budget), governorate_id: form.governorate, delegation_id: form.delegation || null, locality_id: form.locality || null }) }); const updatePayload = await updated.json().catch(() => ({})); if (!updated.ok) { setError(updatePayload.error || 'Projet créé mais informations incomplètes.'); setSaving(false); return; } router.push(`/app/projects/${payload.data.id}`); }
  const inputClass = 'mt-2 w-full rounded-xl border border-black/10 bg-white px-3.5 py-3 text-sm outline-none focus:border-teal focus:ring-4 focus:ring-teal/10';
  return <section className="mx-auto max-w-4xl space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal">Nouveau projet</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Préparons votre chantier</h1><p className="mt-2 max-w-2xl text-sm text-black/55">Quelques étapes simples pour créer un dossier clair, prêt à recevoir des offres.</p></div><div className="grid gap-2 sm:grid-cols-4">{[['Projet', 'Informations générales'], ['Localisation', 'Où se déroule le chantier ?'], ['Budget', 'Quand et avec quel budget ?'], ['Vérification', 'Relire avant création']].map(([label, caption], index) => <div key={label} className={`rounded-xl border p-3 ${step === index + 1 ? 'border-teal bg-teal/5' : step > index + 1 ? 'border-teal/20 bg-white' : 'border-black/5 bg-white/60'}`}><div className="flex items-center gap-2"><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold ${step > index + 1 ? 'bg-teal text-white' : step === index + 1 ? 'bg-ink text-white' : 'bg-sand text-black/40'}`}>{step > index + 1 ? <Check size={14} /> : index + 1}</span><span className="text-sm font-semibold">{label}</span></div><p className="mt-1 pl-8 text-[11px] text-black/45">{caption}</p></div>)}</div><Card><div className="mb-6 flex items-center justify-between border-b border-black/5 pb-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-black/40">Étape {step} sur 4</p><h2 className="mt-1 text-xl font-bold">{step === 1 ? 'Décrivez le projet' : step === 2 ? 'Situez le chantier' : step === 3 ? 'Budget et calendrier' : 'Vérifiez les informations'}</h2></div><span className="text-sm font-semibold text-teal">{step * 25}%</span></div><form onSubmit={event => { if (step < 4) { event.preventDefault(); return; } void submit(event); }}>
    {step === 1 && <div className="grid gap-5"><label className="block text-sm font-semibold">Titre du projet<Input aria-label="Titre du projet" required value={form.title} onChange={event => update('title', event.target.value)} placeholder="Ex. Maison S+3 à Sahloul" /></label><label className="block text-sm font-semibold">Description<textarea aria-label="Description" className={`${inputClass} min-h-32 resize-y`} value={form.description} onChange={event => update('description', event.target.value)} placeholder="Décrivez le besoin global, les pièces concernées ou vos priorités." /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Type de projet<select aria-label="Type de projet" className={inputClass} value={form.type} onChange={event => update('type', event.target.value)}>{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-semibold">Surface (m²)<Input aria-label="Surface (m²)" type="number" min="1" value={form.surface} onChange={event => update('surface', event.target.value)} placeholder="180" /></label></div></div>}
    {step === 2 && <div className="grid gap-5"><div className="flex items-start gap-3 rounded-xl bg-teal/5 p-4 text-sm text-black/60"><MapPin size={19} className="mt-0.5 shrink-0 text-teal" /><p>La localisation publique sera limitée au territoire. L’adresse exacte se complète ensuite dans le projet privé.</p></div><div className="grid gap-4 sm:grid-cols-3"><label className="block text-sm font-semibold">Gouvernorat<select aria-label="Gouvernorat" required className={inputClass} value={form.governorate} onChange={event => update('governorate', event.target.value)}><option value="">Choisir…</option>{governorates.map(item => <option key={item.id} value={item.id}>{item.name_fr}</option>)}</select></label><label className="block text-sm font-semibold">Délégation<select aria-label="Délégation" className={inputClass} disabled={!form.governorate} value={form.delegation} onChange={event => update('delegation', event.target.value)}><option value="">Choisir…</option>{delegations.map(item => <option key={item.id} value={item.id}>{item.name_fr}</option>)}</select></label><label className="block text-sm font-semibold">Localité<select aria-label="Localité" className={inputClass} disabled={!form.delegation} value={form.locality} onChange={event => update('locality', event.target.value)}><option value="">Choisir…</option>{localities.map(item => <option key={item.id} value={item.id}>{item.name_fr}</option>)}</select></label></div></div>}
    {step === 3 && <div className="grid gap-5"><div className="flex items-start gap-3 rounded-xl bg-sand p-4 text-sm text-black/60"><Wallet size={19} className="mt-0.5 shrink-0 text-clay" /><p>Le budget est indicatif et exprimé en dinars tunisiens. Vous pourrez le préciser lot par lot.</p></div><div className="grid gap-4 sm:grid-cols-3"><label className="block text-sm font-semibold sm:col-span-1">Budget indicatif (TND)<Input aria-label="Budget indicatif (TND)" type="number" min="0" step="0.001" value={form.budget} onChange={event => update('budget', event.target.value)} placeholder="150000" /></label><label className="block text-sm font-semibold">Début souhaité<Input aria-label="Début souhaité" type="date" value={form.date} onChange={event => update('date', event.target.value)} /></label><label className="block text-sm font-semibold">Fin souhaitée<Input aria-label="Fin souhaitée" type="date" min={form.date || undefined} value={form.endDate} onChange={event => update('endDate', event.target.value)} /></label></div></div>}
    {step === 4 && <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-sand p-4"><p className="text-xs text-black/45">Projet</p><p className="mt-1 font-bold">{form.title}</p><p className="mt-1 text-sm text-black/55">{types[form.type as keyof typeof types]}{form.surface ? ` · ${form.surface} m²` : ''}</p></div><div className="rounded-xl bg-sand p-4"><p className="text-xs text-black/45">Localisation</p><p className="mt-1 font-bold">{[selected.governorate, selected.delegation, selected.locality].filter(Boolean).join(' · ') || 'À préciser'}</p></div><div className="rounded-xl bg-sand p-4"><p className="text-xs text-black/45">Budget</p><p className="mt-1 font-bold">{form.budget ? `${form.budget} TND` : 'À préciser'}</p></div><div className="rounded-xl bg-sand p-4"><p className="text-xs text-black/45">Calendrier</p><p className="mt-1 font-bold">{form.date || 'À préciser'}{form.endDate ? ` → ${form.endDate}` : ''}</p></div></div>{form.description && <div className="rounded-xl border border-black/5 p-4"><p className="text-xs text-black/45">Description</p><p className="mt-1 whitespace-pre-wrap text-sm text-black/65">{form.description}</p></div>}<p className="flex items-center gap-2 text-sm text-black/55"><Ruler size={17} className="text-teal" />Vous pourrez ajouter les lots et documents depuis la fiche projet.</p></div>}
    {error && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-black/5 pt-5">{step > 1 ? <Button type="button" className="bg-white text-ink ring-1 ring-black/10 hover:bg-sand" onClick={() => { setError(''); setStep(value => value - 1); }}><ArrowLeft size={16} className="mr-2" />Précédent</Button> : <span />}{step < 4 ? <Button type="button" onClick={next}>Continuer <ArrowRight size={16} className="ml-2" /></Button> : <Button disabled={saving}>{saving ? 'Création…' : 'Créer le projet'}</Button>}</div></form></Card></section>;
}
