import { randomUUID } from 'node:crypto';
import { test, expect } from './support/fixtures';
import { createProjectWithMainLot, login } from './support/flow';
import { actorCommand, adminRows } from './support/collaboration';
import { recordE2EValue } from './support/state';

test('Back-office : prise en charge, nouvelle version et sous-lots visibles côté client',async({page,browser,e2eClient,e2eReviewer,e2eOtherReviewer},info)=>{
 expect(e2eClient).toBeTruthy();expect(e2eReviewer).toBeTruthy();expect(e2eOtherReviewer).toBeTruthy();await login(page,e2eClient!);const project=await createProjectWithMainLot(page,info,'bo-review','Périmètre client original','Lot BO original');await page.goto(`/app/projects/${project.projectId}/review`);await page.getByRole('button',{name:'Soumettre pour revue DAO'}).click();
 const rc=await browser.newContext(),reviewer=await rc.newPage();await login(reviewer,e2eReviewer!);await reviewer.goto(`/app/dao/projects/${project.projectId}`);await reviewer.getByRole('button',{name:'Prendre en charge',exact:true}).click();await expect(reviewer.getByText('Revue prise en charge.',{exact:true})).toBeVisible();
 const oc=await browser.newContext(),other=await oc.newPage();await login(other,e2eOtherReviewer!);await other.goto(`/app/dao/projects/${project.projectId}`);await expect(other.getByText(/Lecture seule : ce dossier/)).toBeVisible();await expect(other.getByRole('button',{name:'Modifier le dossier'})).toHaveCount(0);const forged=await actorCommand(other,e2eOtherReviewer!,'/api/dao/backoffice',{action:'claim',input:{project_id:project.projectId},idempotency_key:randomUUID()});expect(forged.status()).toBe(403);await oc.close();
 await reviewer.getByRole('button',{name:'Modifier le dossier'}).click();await reviewer.getByLabel('Titre',{exact:true}).fill(project.title+' staff');await reviewer.getByLabel('Périmètre du lot',{exact:true}).fill('Périmètre staff corrigé');await reviewer.getByRole('button',{name:'Ajouter un sous-lot'}).click();await reviewer.getByLabel('Titre du sous-lot',{exact:true}).fill('Réseaux techniques');await reviewer.getByLabel('Périmètre du sous-lot',{exact:true}).fill('Passage et essais des réseaux');await reviewer.getByLabel('Budget du sous-lot (TND)').fill('100.001');await reviewer.getByRole('button',{name:'Enregistrer une nouvelle version'}).click();await expect(reviewer.getByRole('status')).toContainText('Nouvelle version créée');await reviewer.getByRole('button',{name:'Approuver',exact:true}).click();await expect(reviewer.getByRole('status')).toContainText('Dossier approuvé');
 await page.goto(`/app/projects/${project.projectId}`);await page.getByRole('button',{name:'Historique',exact:true}).click();await expect(page.getByRole('heading',{name:'Modifications et revues DAO'})).toBeVisible();const version=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Version 2'})}).first();await version.locator('summary').click();await expect(version.getByText('Passage et essais des réseaux',{exact:true})).toBeVisible();await expect(version.getByText('100.001 TND')).toBeVisible();expect((await adminRows('project_versions',`project_id=eq.${project.projectId}&version_no=eq.1&select=title`))[0].title).toBe(project.title);
 await reviewer.goto(`/app/dao/publications/new?project_id=${project.projectId}`);await reviewer.getByRole('button',{name:'Publier le DAO'}).click();await expect(reviewer).toHaveURL(/\/app\/publications\//);recordE2EValue(info,'publications',reviewer.url().split('/').pop()!);await expect(reviewer.getByText('Passage et essais des réseaux',{exact:true})).toBeVisible();await rc.close();
});

test('Back-office : attribution assistée et retrait motivé conservent offre et publication',async({page,browser,e2eClient,e2eReviewer,e2eArtisan},info)=>{
 expect(e2eClient).toBeTruthy();expect(e2eReviewer).toBeTruthy();expect(e2eArtisan).toBeTruthy();await login(page,e2eClient!);const project=await createProjectWithMainLot(page,info,'bo-withdraw','Travaux publiés','Lot BO retrait');await page.goto(`/app/projects/${project.projectId}/review`);await page.getByRole('button',{name:'Soumettre pour revue DAO'}).click();const rc=await browser.newContext(),staff=await rc.newPage();await login(staff,e2eReviewer!);await staff.goto(`/app/dao/projects/${project.projectId}`);await staff.getByRole('button',{name:'Prendre en charge',exact:true}).click();await expect(staff.getByRole('button',{name:'Approuver',exact:true})).toBeVisible();await staff.getByRole('button',{name:'Approuver',exact:true}).click();await expect(staff.getByRole('status')).toContainText('Dossier approuvé');await staff.goto(`/app/dao/publications/new?project_id=${project.projectId}`);await staff.getByRole('button',{name:'Publier le DAO'}).click();await expect(staff).toHaveURL(/\/app\/publications\//);const pub=staff.url().split('/').pop()!;recordE2EValue(info,'publications',pub);
 const ac=await browser.newContext(),artisan=await ac.newPage();await login(artisan,e2eArtisan!);await artisan.goto(`/app/artisan/publications/${pub}`);await artisan.getByLabel('Prix proposé (TND)').fill('1000.001');await artisan.getByLabel('Délai (jours)').fill('10');await artisan.getByLabel('Proposition technique / inclusions').fill('Offre BO immuable');await artisan.getByRole('button',{name:'Soumettre l’offre'}).click();await expect(artisan.getByRole('heading',{name:'Offre envoyée'})).toBeVisible();const before=await adminRows('bid_items',`project_id=eq.${project.projectId}&select=id,price_millimes,inclusions`);
 await staff.reload();await expect(staff.getByText(/Actions pour le compte du client/)).toBeVisible();await staff.getByLabel('Contexte de la demande du client').fill('Demande du client de comparer et attribuer cette offre');await staff.getByRole('button',{name:'Attribuer cette offre'}).click();await staff.getByRole('button',{name:'Confirmer l’attribution'}).click();await expect(staff.getByText('Lot attribué',{exact:true})).toBeVisible();await staff.getByRole('button',{name:'Retirer de la publication'}).click();let withdrawal=staff.getByRole('dialog',{name:'Retirer un lot'});await withdrawal.getByLabel('Motif',{exact:true}).selectOption('correction');await withdrawal.getByRole('button',{name:'Confirmer le retrait'}).click();await expect(withdrawal.getByRole('alert')).toContainText('Annuler d’abord');await withdrawal.getByRole('button',{name:'Annuler',exact:true}).click();await staff.getByRole('button',{name:'Annuler l’attribution',exact:true}).click();const cancellation=staff.getByRole('group',{name:'Annulation de l’attribution'});await cancellation.getByLabel('Motif d’annulation').selectOption('award_error');await cancellation.getByRole('button',{name:'Confirmer l’annulation'}).click();await expect(staff.getByRole('button',{name:'Attribuer cette offre'})).toBeVisible();
 await staff.getByRole('button',{name:'Retirer de la publication'}).click();withdrawal=staff.getByRole('dialog',{name:'Retirer un lot'});await withdrawal.getByLabel('Motif',{exact:true}).selectOption('other');await expect(withdrawal.getByRole('button',{name:'Confirmer le retrait'})).toBeDisabled();await withdrawal.getByLabel('Commentaire obligatoire').fill('Corriger le périmètre');await withdrawal.getByRole('button',{name:'Confirmer le retrait'}).click();await expect(staff.getByText('Retiré de la publication',{exact:true})).toBeVisible();expect(await adminRows('bid_items',`project_id=eq.${project.projectId}&select=id,price_millimes,inclusions`)).toEqual(before);expect((await adminRows('publications',`id=eq.${pub}&select=status`))[0].status).toBe('closed');await artisan.reload();await expect(artisan.getByRole('heading',{name:'Offre envoyée'})).toBeVisible();await expect(artisan.getByText('Lot fermé aux nouvelles offres')).toBeVisible();await ac.close();await rc.close();
});

test('Admin : rôles cumulables, gestion professionnelle et contrôle des accès Gestionnaire',async({page,browser,e2eAdmin,e2eReviewer,e2eArtisan})=>{
 expect(e2eAdmin).toBeTruthy();expect(e2eReviewer).toBeTruthy();expect(e2eArtisan).toBeTruthy();await login(page,e2eAdmin!);if(test.info().project.name==='mobile')await page.getByRole('button',{name:'Ouvrir le menu'}).click();await expect(page.getByRole('link',{name:'Utilisateurs & rôles'})).toBeVisible();await page.goto('/app/dao/users');await page.getByLabel('Rechercher utilisateurs & rôles').fill(e2eArtisan!.email);await page.getByRole('button').filter({hasText:e2eArtisan!.email}).click();let dossier=page.getByRole('dialog',{name:'Dossier du compte'});await dossier.getByLabel('Client',{exact:true}).check();let confirmation=page.getByRole('dialog',{name:'Confirmer la modification'});await confirmation.getByRole('button',{name:'Confirmer',exact:true}).click();await expect(confirmation).toHaveCount(0);await page.getByRole('button').filter({hasText:e2eArtisan!.email}).click();dossier=page.getByRole('dialog',{name:'Dossier du compte'});await expect(dossier.getByLabel('Client',{exact:true})).toBeChecked();await expect(dossier.getByLabel('Artisan / Entreprise',{exact:true})).toBeChecked();await dossier.getByRole('button',{name:'Fermer',exact:true}).click();
 await page.goto('/app/dao/professionals');await page.getByLabel('Rechercher professionnels').fill(e2eArtisan!.email);await page.getByRole('button').filter({hasText:e2eArtisan!.email}).click();dossier=page.getByRole('dialog',{name:'Dossier du compte'});await dossier.getByRole('button',{name:'Suspendre',exact:true}).click();confirmation=page.getByRole('dialog',{name:'Confirmer la modification'});await confirmation.getByLabel('Motif obligatoire').fill('Revue du profil');await confirmation.getByRole('button',{name:'Confirmer',exact:true}).click();await expect(confirmation).toHaveCount(0);
 const rc=await browser.newContext(),reviewer=await rc.newPage();await login(reviewer,e2eReviewer!);if(test.info().project.name==='mobile')await reviewer.getByRole('button',{name:'Ouvrir le menu'}).click();await expect(reviewer.getByRole('link',{name:'Utilisateurs & rôles'})).toHaveCount(0);await reviewer.goto('/app/dao/users');await expect(reviewer.getByRole('alert')).toContainText('Administration');await reviewer.goto('/app/dao/professionals');await reviewer.getByLabel('Rechercher professionnels').fill(e2eArtisan!.email);await reviewer.getByRole('button').filter({hasText:e2eArtisan!.email}).click();dossier=reviewer.getByRole('dialog',{name:'Dossier du compte'});await expect(dossier.getByRole('button',{name:'Vérifier',exact:true})).toBeDisabled();await expect(dossier.getByRole('button',{name:'Suspendre',exact:true})).toHaveCount(0);await rc.close();
 await page.getByRole('button').filter({hasText:e2eArtisan!.email}).click();dossier=page.getByRole('dialog',{name:'Dossier du compte'});await dossier.getByRole('button',{name:'Réactiver',exact:true}).click();await page.getByRole('dialog',{name:'Confirmer la modification'}).getByRole('button',{name:'Confirmer',exact:true}).click();await expect(page.getByRole('dialog',{name:'Confirmer la modification'})).toHaveCount(0);
 await page.getByRole('button').filter({hasText:e2eArtisan!.email}).click();dossier=page.getByRole('dialog',{name:'Dossier du compte'});await dossier.getByRole('button',{name:'Vérifier',exact:true}).click();await page.getByRole('dialog',{name:'Confirmer la modification'}).getByRole('button',{name:'Confirmer',exact:true}).click();await expect(page.getByRole('dialog',{name:'Confirmer la modification'})).toHaveCount(0);
 await page.goto('/app/dao/users');await page.getByLabel('Rechercher utilisateurs & rôles').fill(e2eArtisan!.email);await page.getByRole('button').filter({hasText:e2eArtisan!.email}).click();await page.getByRole('dialog',{name:'Dossier du compte'}).getByLabel('Client',{exact:true}).uncheck();await page.getByRole('dialog',{name:'Confirmer la modification'}).getByRole('button',{name:'Confirmer',exact:true}).click();await expect(page.getByRole('dialog',{name:'Confirmer la modification'})).toHaveCount(0);
});

test('Admin : invitation Supabase standard puis activation et connexion du nouveau staff',async({page,browser,request,e2eAdmin},info)=>{
 expect(e2eAdmin).toBeTruthy();await login(page,e2eAdmin!);await page.goto('/app/dao/users');const email=`dao-e2e-invited-${randomUUID()}@example.invalid`;const form=page.getByRole('heading',{name:'Inviter un membre staff'}).locator('..').locator('form');await form.getByLabel('Nom',{exact:true}).fill('Gestionnaire invité E2E');await form.getByLabel('Email',{exact:true}).fill(email);await form.getByLabel('Rôle',{exact:true}).selectOption('dao_reviewer');await form.getByRole('button',{name:'Envoyer l’invitation'}).click();await expect(page.getByRole('status')).toContainText('Compte staff invité');const invitation=await adminRows('staff_invitation_requests',`email=eq.${email}&select=status,target_user_id`);expect(invitation).toHaveLength(1);expect(invitation[0].status).toBe('completed');recordE2EValue(info,'users',invitation[0].target_user_id);
 let messageId='';await expect.poll(async()=>{const r=await request.get('http://127.0.0.1:54324/api/v1/search',{params:{query:`to:${email}`}});expect(r.ok()).toBeTruthy();const inbox=await r.json();const messages=inbox.messages.filter((m:any)=>/invite/i.test(m.Subject));if(messages.length===1)messageId=messages[0].ID;return messages.length;}).toBe(1);const captured=await request.get(`http://127.0.0.1:54324/api/v1/message/${messageId}`);expect(captured.ok()).toBeTruthy();const mail=await captured.json();const links=Array.from(String(mail.HTML).matchAll(/href="([^"]+)"/g),m=>m[1].replaceAll('&amp;','&'));const inviteLink=links.find(link=>{const u=new URL(link);return u.origin==='http://127.0.0.1:54321'&&u.pathname==='/auth/v1/verify'&&u.searchParams.get('type')==='invite';});expect(inviteLink).toBeTruthy();const context=await browser.newContext(),staff=await context.newPage();await staff.goto(inviteLink!);await expect(staff).toHaveURL(/\/auth\/activate-staff/);const password='Invited!'+randomUUID();await staff.getByLabel('Nouveau mot de passe',{exact:true}).fill(password);await staff.getByLabel('Confirmer le mot de passe',{exact:true}).fill(password);await staff.getByRole('button',{name:'Activer mon accès'}).click();await expect(staff.getByRole('status')).toContainText('mot de passe est enregistré');await staff.getByRole('link',{name:'Ouvrir le back-office'}).click();await expect(staff.getByRole('heading',{name:'Pilotage D.A.O'})).toBeVisible();await context.close();
});
