import { test, expect } from './support/fixtures';
import { login } from './support/flow';
import { acceptWithLogin, adminRows, createCollaborative, signOut } from './support/collaboration';

test('Artisan initiateur : client à confirmer, confirmation distincte du DAO et dashboard adapté', async ({ page, e2eArtisan, e2eClient }, info) => {
  test.skip(!e2eClient || !e2eArtisan, 'Disposable E2E credentials are not available');
  await login(page, e2eArtisan!);
  await page.goto('/app');
  await expect(page.getByRole('heading', { name: 'Mes chantiers clients', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Ajouter un chantier client', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Voir les appels d’offres', exact: true })).toBeVisible();
  await expect(page.getByText(/préparez des lots clairs/)).toHaveCount(0);
  const project = await createCollaborative(page, info, true, e2eClient!.email);
  await expect(page.getByRole('main').getByText('Client à confirmer', { exact: true })).toBeVisible();
  expect(await adminRows('projects', `id=eq.${project.projectId}&select=client_id,initiator_id,confirmed_at,status`)).toEqual([{ client_id: null, initiator_id: e2eArtisan!.id, confirmed_at: null, status: 'draft' }]);
  const versionsBefore = await adminRows('project_versions', `project_id=eq.${project.projectId}&select=id,status,version_no`);
  await page.goto('/app');
  await expect(page.getByRole('link').filter({ hasText: project.title })).toContainText('Client à confirmer');
  await signOut(page);
  await page.goto(project.link);
  await expect(page.getByRole('heading', { name: project.title })).toBeVisible();
  await expect(page.getByText('Travaux en cours', { exact: true })).toBeVisible();
  await expect(page.getByText('Partiellement payé', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Adresse exacte')).toHaveCount(0);
  await acceptWithLogin(page, project.link, e2eClient!);
  await expect(page.getByRole('heading', { name: project.title })).toBeVisible();
  await expect(page.getByRole('main').getByText('Client à confirmer', { exact: true })).toHaveCount(0);
  expect(await adminRows('projects', `id=eq.${project.projectId}&select=client_id,initiator_id,confirmed_at,confirmed_by,status`)).toEqual([expect.objectContaining({ client_id: e2eClient!.id, initiator_id: e2eArtisan!.id, confirmed_by: e2eClient!.id, confirmed_at: expect.any(String), status: 'draft' })]);
  expect(await adminRows('project_versions', `project_id=eq.${project.projectId}&select=id,status,version_no`)).toEqual(versionsBefore);
  const members = await adminRows('project_members', `project_id=eq.${project.projectId}&status=eq.accepted&select=user_id,participation_role`);
  expect(members).toEqual(expect.arrayContaining([{ user_id: e2eClient!.id, participation_role: 'client' }, { user_id: e2eArtisan!.id, participation_role: 'contractor' }]));
  expect(members).toHaveLength(2);
  await page.goto('/app');
  await expect(page.getByRole('link').filter({ hasText: project.title })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth), 'Le tableau de bord client doit tenir dans la largeur de l’écran').toBe(0);
  await page.goto(`/app/projects/${project.projectId}`);
  await expect(page.getByRole('heading', { name: project.title, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Suivi', exact: true }).click();
  await page.getByLabel('Avancement actuel du chantier').selectOption('completed');
  await page.getByLabel('Situation du paiement — optionnel').selectOption('unpaid');
  await page.getByRole('button', { name: 'Enregistrer le suivi' }).click();
  await expect(page.getByRole('status')).toContainText('Suivi du chantier enregistré.');
  expect(await adminRows('projects', `id=eq.${project.projectId}&select=project_stage,payment_status,status`)).toEqual([{ project_stage: 'completed', payment_status: 'unpaid', status: 'draft' }]);
  expect(await adminRows('publications', `project_id=eq.${project.projectId}&select=id`)).toHaveLength(0);
  await signOut(page);
  await login(page, e2eArtisan!);
  await page.goto('/app/projects');
  const row = page.locator(`[data-testid="project-row-${project.projectId}"]:visible`);
  await expect(row).toContainText(project.title);
  await expect(row).toContainText('Travaux terminés');
  await expect(row).not.toContainText('Client à confirmer');
  expect((await adminRows('user_roles', `user_id=eq.${e2eArtisan!.id}&select=role`)).map(row => row.role)).toEqual(['contractor']);
});
