import { test, expect } from './support/fixtures';
import { login } from './support/flow';
import { acceptWithLogin, actorCommand, adminRows, approveDocument, createCollaborative, signOut } from './support/collaboration';

test('Documents partagés et coordonnées privées : autorisation explicite puis retrait du membre', async ({ page, e2eClient, e2eArtisan }, info) => {
  test.skip(!e2eClient || !e2eArtisan, 'Disposable E2E credentials are not available');
  await login(page, e2eClient!);
  const project = await createCollaborative(page, info, false, e2eArtisan!.email);
  await page.getByRole('button', { name: 'Vue d’ensemble' }).click();
  await page.getByLabel('Adresse exacte').fill('Adresse confidentielle E2E collaboration');
  await page.locator('form').filter({ has: page.getByLabel('Adresse exacte') }).getByRole('button', { name: 'Enregistrer', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Coordonnées privées enregistrées.');
  await page.getByRole('button', { name: 'Documents', exact: true }).click();
  await page.getByLabel('Ajouter un document').setInputFiles({ name: 'owner-only-collab.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%Collaboration private\n') });
  await expect(page.getByTestId('project-document-row').filter({ hasText: 'owner-only-collab.pdf' })).toContainText('Moi uniquement');
  await page.getByLabel('Partage du nouveau document').selectOption('project_members');
  await page.getByLabel('Ajouter un document').setInputFiles({ name: 'shared-collab.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%Collaboration shared\n') });
  await expect(page.getByTestId('project-document-row').filter({ hasText: 'shared-collab.pdf' })).toContainText('En attente de contrôle');
  const documents = await adminRows('documents', `project_id=eq.${project.projectId}&select=id,original_name,share_scope`);
  const shared = documents.find(document => document.original_name === 'shared-collab.pdf');
  const privateDocument = documents.find(document => document.original_name === 'owner-only-collab.pdf');
  expect(Boolean(shared && privateDocument)).toBeTruthy();
  await signOut(page);
  await acceptWithLogin(page, project.link, e2eArtisan!);
  await expect(page.getByLabel('Adresse exacte')).toHaveCount(0);
  await expect(page.getByText('Vous n’avez pas accès aux coordonnées privées de ce chantier.')).toBeVisible();
  await page.getByRole('button', { name: 'Documents', exact: true }).click();
  await expect(page.getByTestId('project-document-row')).toHaveCount(0);
  // Shared documents retain quarantine until the existing control approves them.
  expect((await actorCommand(page, e2eArtisan!, '/api/documents/project/download', { document_id: shared!.id })).status()).toBe(403);
  await approveDocument(shared!.id);
  await approveDocument(privateDocument!.id);
  await page.reload();
  await page.getByRole('button', { name: 'Documents', exact: true }).click();
  await expect(page.getByTestId('project-document-row').filter({ hasText: 'shared-collab.pdf' })).toBeVisible();
  await expect(page.getByText('owner-only-collab.pdf', { exact: true })).toHaveCount(0);
  expect((await actorCommand(page, e2eArtisan!, '/api/documents/project/download', { document_id: shared!.id })).status()).toBe(200);
  expect((await actorCommand(page, e2eArtisan!, '/api/documents/project/download', { document_id: privateDocument!.id })).status()).toBe(403);
  await signOut(page);
  await login(page, e2eClient!);
  await page.goto(`/app/projects/${project.projectId}?tab=team`);
  const members = await adminRows('project_members', `project_id=eq.${project.projectId}&user_id=eq.${e2eArtisan!.id}&select=id,can_view_private_details`);
  expect(members).toHaveLength(1); expect(members[0].can_view_private_details).toBe(false);
  const permission = page.getByRole('checkbox', { name: /^Accès aux coordonnées privées pour/ });
  await permission.check();
  await expect(permission).toBeChecked();
  await signOut(page);
  await login(page, e2eArtisan!);
  await page.goto(`/app/projects/${project.projectId}`);
  await expect(page.getByLabel('Adresse exacte')).toHaveValue('Adresse confidentielle E2E collaboration');
  await expect(page.getByLabel('Adresse exacte')).toHaveAttribute('readonly', '');
  await signOut(page);
  await login(page, e2eClient!);
  await page.goto(`/app/projects/${project.projectId}?tab=team`);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Retirer le participant' }).click();
  await expect(page.getByRole('button', { name: 'Retirer le participant' })).toHaveCount(0);
  expect((await actorCommand(page, e2eArtisan!, '/api/documents/project/download', { document_id: shared!.id })).status()).toBe(403);
  await signOut(page);
  await login(page, e2eArtisan!);
  await page.goto('/app/projects');
  await expect(page.getByText(project.title, { exact: true })).toHaveCount(0);
  await page.goto(`/app/projects/${project.projectId}`);
  await expect(page.getByRole('main').getByRole('alert')).toContainText('Projet inaccessible');
});
