import { test, expect } from './support/fixtures';
import { login } from './support/flow';
import { recordE2EValue } from './support/state';
import { acceptWithLogin, adminRows, createCollaborative, signOut } from './support/collaboration';

test('Client avec équipe existante : invitation, chantier commun et publication des seuls lots manquants', async ({ page, browser, e2eClient, e2eArtisan, e2eReviewer }, info) => {
  test.skip(!e2eClient || !e2eArtisan || !e2eReviewer, 'Disposable E2E credentials are not available');
  await login(page, e2eClient!);
  const project = await createCollaborative(page, info, false, e2eArtisan!.email);
  await expect(page.getByRole('heading', { name: 'Équipe du chantier' })).toBeVisible();
  await expect(page.getByRole('main').getByText('Client à confirmer', { exact: true })).toHaveCount(0);
  expect(await adminRows('projects', `id=eq.${project.projectId}&select=client_id,initiator_id,project_origin,project_stage,payment_status`)).toEqual([expect.objectContaining({ client_id: e2eClient!.id, initiator_id: e2eClient!.id, project_origin: 'client_existing_team', project_stage: 'in_progress', payment_status: 'partial' })]);
  await signOut(page);
  await acceptWithLogin(page, project.link, e2eArtisan!);
  await expect(page.getByRole('heading', { name: project.title })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Modifier le projet' })).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Revoir le DAO' })).toHaveCount(0);
  await page.goto('/app/projects');
  const artisanRow = page.locator(`[data-testid="project-row-${project.projectId}"]:visible`);
  await expect(artisanRow).toContainText(project.title);
  await expect(artisanRow).toContainText('Travaux en cours');
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth), 'Mes chantiers doit tenir dans la largeur de l’écran').toBe(0);
  await signOut(page);
  await login(page, e2eClient!);
  await page.goto(`/app/projects/${project.projectId}`);
  const members = await adminRows('project_members', `project_id=eq.${project.projectId}&user_id=eq.${e2eArtisan!.id}&select=id`);
  expect(members).toHaveLength(1);
  const principalRows = await adminRows('project_requests', `project_id=eq.${project.projectId}&contractor_member_id=eq.${members[0].id}&select=id`);
  expect(principalRows).toHaveLength(1);
  const principalLotRow = page.getByRole('row').filter({ hasText: 'Lot principal E2E' });
  await expect(principalLotRow).toHaveCount(1);
  await expect(principalLotRow.getByRole('link', { name: 'Trouver un professionnel' })).toHaveCount(0);
  await expect(page.getByLabel('Professionnel de Lot principal E2E')).toHaveValue(members[0].id);
  await page.getByRole('button', { name: 'Ajouter un lot', exact: true }).click();
  await page.getByLabel('Métier', { exact: true }).selectOption({ label: 'Plomberie' });
  await page.getByLabel('Intitulé du lot').fill('Plomberie à rechercher');
  await page.getByLabel('Périmètre des travaux').fill('Un professionnel reste à trouver pour la plomberie.');
  await page.getByRole('button', { name: 'Ajouter la demande' }).click();
  const missingRow = page.getByRole('row').filter({ hasText: 'Plomberie à rechercher' });
  await expect(missingRow).toHaveCount(1);
  await expect(missingRow.getByRole('link', { name: 'Trouver un professionnel' })).toBeVisible();
  await expect(page.getByLabel('Professionnel de Lot principal E2E')).toHaveValue(members[0].id);
  await missingRow.getByRole('link', { name: 'Trouver un professionnel' }).click();
  await expect(page.getByRole('button', { name: 'Soumettre pour revue DAO' })).toBeEnabled();
  expect(await adminRows('publications', `project_id=eq.${project.projectId}&select=id`)).toHaveLength(0);
  await page.getByRole('button', { name: 'Soumettre pour revue DAO' }).click();
  await expect(page.getByRole('main').getByText('Validation client', { exact: true })).toBeVisible();
  const reviewerContext = await browser.newContext({ viewport: page.viewportSize() || undefined });
  try {
    const reviewer = await reviewerContext.newPage();
    await login(reviewer, e2eReviewer!);
    await reviewer.goto('/app/dao/review');
    const card = reviewer.getByRole('heading', { name: project.title, exact: true }).locator('xpath=../../..');
    await card.getByRole('button', { name: 'Passer en revue DAO' }).click();
    await expect(card.getByText('dao_review', { exact: true })).toBeVisible();
    await card.getByRole('button', { name: 'Approuver' }).click();
    await expect(reviewer.getByRole('heading', { name: project.title, exact: true })).toHaveCount(0);
    await reviewer.goto(`/app/dao/publications/new?project_id=${project.projectId}`);
    await expect(reviewer.locator('label').filter({ hasText: 'Lot principal E2E' }).getByRole('checkbox')).not.toBeChecked();
    await expect(reviewer.locator('label').filter({ hasText: 'Plomberie à rechercher' }).getByRole('checkbox')).toBeChecked();
    await reviewer.getByRole('button', { name: 'Publier le DAO' }).click();
    await expect(reviewer).toHaveURL(/\/app\/publications\/[0-9a-f-]{36}$/);
    const publicationId = reviewer.url().split('/').pop()!;
    recordE2EValue(info, 'publications', publicationId);
    const lots = await adminRows('publication_requests', `publication_id=eq.${publicationId}&select=request_version_id,safe_title`);
    expect(lots).toHaveLength(1); expect(lots[0].safe_title).toBe('Plomberie à rechercher');
    const publishedSnapshot = await adminRows('project_request_versions', `id=eq.${lots[0].request_version_id}&select=request_id`);
    const missing = await adminRows('project_requests', `project_id=eq.${project.projectId}&contractor_member_id=is.null&status=neq.withdrawn&select=id`);
    expect(publishedSnapshot[0].request_id).toBe(missing[0].id);
    expect(await adminRows('project_requests', `project_id=eq.${project.projectId}&contractor_member_id=eq.${members[0].id}&select=id`)).toHaveLength(1);
  } finally { await reviewerContext.close(); }
});
