import { randomUUID } from 'node:crypto';
import { test,expect } from './support/fixtures';
import { login } from './support/flow';
import { adminRows,actorCommand } from './support/collaboration';

test('PRO : six sections, dossier privé, réalisation modérée, consultation client puis retrait',async({page,browser,e2eArtisan,e2eClient,e2eAdmin,e2eSecondArtisan},info)=>{
  expect(e2eArtisan).toBeTruthy();expect(e2eClient).toBeTruthy();expect(e2eAdmin).toBeTruthy();expect(e2eSecondArtisan).toBeTruthy();
  const cp=(await adminRows('contractor_profiles',`user_id=eq.${e2eArtisan!.id}&select=id`))[0];
  const title=`Réalisation PRO ${info.project.name} ${randomUUID()}`;
  await login(page,e2eArtisan!);await page.goto('/app/artisan/profile');
  await expect(page.getByRole('heading',{name:'Mon dossier professionnel'})).toBeVisible();
  for(const name of ['Présentation','Coordonnées & zones','Informations légales','Réalisations','Vérification','Aperçu client'])await expect(page.getByRole('button',{name,exact:true})).toBeVisible();
  await page.screenshot({path:info.outputPath('professional-editor.png'),fullPage:true});
  await page.getByRole('button',{name:'Coordonnées & zones',exact:true}).click();await page.getByLabel('Site officiel HTTPS',{exact:true}).fill('https://example.com');await page.getByLabel('Téléphone professionnel',{exact:true}).fill('+21620000005');await page.getByLabel('Afficher téléphone professionnel aux clients autorisés').check();await page.getByRole('button',{name:'Enregistrer les coordonnées'}).click();await expect(page.getByRole('status')).toContainText('Enregistré.');
  await page.getByRole('button',{name:'Coordonnées & zones',exact:true}).click();await page.getByLabel('Ville',{exact:true}).fill('Tunis');await page.getByLabel('Adresse exacte du bureau — privée').fill('PRIVATE UI ADDRESS');await page.getByRole('button',{name:'Enregistrer les zones'}).click();await expect(page.getByRole('status')).toContainText('Enregistré.');
  await page.getByRole('button',{name:'Informations légales',exact:true}).click();await page.getByLabel('Dénomination légale',{exact:true}).fill('PRIVATE UI LEGAL');await page.getByLabel('Identifiant fiscal',{exact:true}).fill('PRIVATE UI TAX');await expect(page.getByLabel('Immatriculation / RNE — si applicable')).toHaveValue('');await page.getByRole('button',{name:'Enregistrer les informations légales'}).click();await expect(page.getByRole('status')).toContainText('vérification DAO est relancée');
  await page.getByRole('button',{name:'Réalisations',exact:true}).click();await page.getByLabel('Titre de la réalisation').fill(title);await page.getByLabel('Description de la réalisation').fill('Travaux déclarés, lieu approximatif uniquement.');await page.getByLabel('Métier de la réalisation').selectOption({index:1});await page.getByLabel('Année des travaux').fill('2024');await page.getByRole('textbox',{name:'Lieu approximatif',exact:true}).fill('Tunis');await page.getByLabel('J’autorise la publication de cette réalisation').check();await page.getByRole('button',{name:'Enregistrer la réalisation',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
  await page.getByLabel(`Média pour ${title}`).setInputFiles({name:'avant-pro.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});await page.getByLabel('Type de média').selectOption('before');await page.getByLabel('J’autorise la publication de ce média et confirme disposer des droits nécessaires.').check();await page.getByRole('button',{name:'Envoyer le fichier',exact:true}).click();await expect(page.getByText('À contrôler',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:`Soumettre ${title}`,exact:true}).click();await expect(page.getByText('En revue',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Vérification',exact:true}).click();await page.getByRole('button',{name:'Soumettre la fiche à DAO'}).click();await expect(page.getByRole('status')).toContainText('Enregistré.');
  await page.getByRole('button',{name:'Aperçu client',exact:true}).click();await expect(page.getByText(/Prévisualisation propriétaire \/ staff/)).toBeVisible();await expect(page.getByText('PRIVATE UI TAX',{exact:true})).toHaveCount(0);
  const ac=await browser.newContext(),staff=await ac.newPage();await login(staff,e2eAdmin!);await staff.goto(`/app/dao/professionals/${cp.id}/dossier`);
  await expect(staff.getByText('PRIVATE UI TAX',{exact:true})).toBeVisible();await staff.getByRole('button',{name:'Vérifier le professionnel',exact:true}).click();await expect(staff.getByRole('status')).toContainText('Décision enregistrée.');await staff.getByRole('button',{name:'Publier la fiche client',exact:true}).click();await expect(staff.getByText('Approuvé',{exact:true})).toBeVisible();await staff.getByRole('button',{name:'Approuver avant-pro.png',exact:true}).click();await expect(staff.getByRole('status')).toContainText('Décision enregistrée.');await staff.getByRole('button',{name:`Publier ${title}`,exact:true}).click();await expect(staff.getByText('Publié',{exact:true})).toBeVisible();
  const cc=await browser.newContext(),client=await cc.newPage();await login(client,e2eClient!);await client.goto(`/app/professionals/${cp.id}`);await expect(client.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(client.getByText('+21620000005',{exact:true})).toBeVisible();await expect(client.getByText('PRIVATE UI TAX',{exact:true})).toHaveCount(0);await expect(client.getByText('PRIVATE UI ADDRESS',{exact:true})).toHaveCount(0);await expect(client.getByText('Avant',{exact:true})).toBeVisible();await expect(client.getByRole('img',{name:'avant-pro.png',exact:true})).toBeVisible();
  const forbidden=await actorCommand(client,e2eClient!,'/api/professionals',{action:'details',input:{tax_identifier:'forged'}});expect(forbidden.status()).toBe(403);
  await client.screenshot({path:info.outputPath('professional-client.png'),fullPage:true});
  const foreign=await actorCommand(client,e2eSecondArtisan!,'/api/professionals',{action:'file_withdraw',input:{kind:'portfolio',id:(await adminRows('portfolio_assets',`contractor_id=eq.${cp.id}&original_name=eq.avant-pro.png&select=id`))[0].id}});expect(foreign.status()).toBe(403);
  await page.getByRole('button',{name:'Réalisations',exact:true}).click();await page.getByRole('button',{name:'Retirer avant-pro.png',exact:true}).click();await expect(page.getByText('Retiré',{exact:true})).toBeVisible();await client.reload();await expect(client.getByRole('img',{name:'avant-pro.png',exact:true})).toHaveCount(0);await expect(client.getByRole('heading',{name:title,exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await ac.close();await cc.close();
});

test('PRO : un brouillon ne devient pas public par une prévisualisation forgée',async({page,e2eSecondArtisan,e2eClient})=>{
  expect(e2eSecondArtisan).toBeTruthy();expect(e2eClient).toBeTruthy();const cp=(await adminRows('contractor_profiles',`user_id=eq.${e2eSecondArtisan!.id}&select=id`))[0];
  await login(page,e2eClient!);await page.goto(`/app/professionals/${cp.id}?preview=true`);await expect(page.getByRole('alert').filter({hasText:'Fiche non publiée ou non autorisée'})).toContainText('Fiche non publiée ou non autorisée');await expect(page.getByRole('link',{name:'Retour aux professionnels'})).toBeVisible();
});
