import { test, expect } from './support/fixtures';
import { createProjectWithMainLot, login } from './support/flow';
import { recordE2EValue } from './support/state';
import { adminRows } from './support/collaboration';

test('Publication, comparaison, attribution par lot et confidentialité publique', async ({ page, browser, e2eClient, e2eReviewer, e2eArtisan, e2eSecondArtisan }, testInfo) => {
  test.skip(!e2eClient || !e2eReviewer || !e2eArtisan || !e2eSecondArtisan, 'E2E Supabase credentials are not available');

  await login(page, e2eClient!);
  const project = await createProjectWithMainLot(page, testInfo, 'publication-bid', 'Fourniture, pose, essais et remise en état.', 'Lot plomberie E2E publication');
  const initialLotRow = page.locator('tr').filter({ hasText: project.lotTitle });
  await expect(initialLotRow).toHaveCount(1);
  await initialLotRow.getByTitle('Modifier').click();
  project.lotTitle = 'Lot plomberie E2E publication v2';
  await page.getByLabel('Intitulé du lot').fill(project.lotTitle);
  await page.getByRole('button', { name: 'Enregistrer les modifications' }).click();
  await expect(page.getByText('v2', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Vue d’ensemble' }).click();
  await page.getByLabel('Adresse exacte').fill('12 rue de Sahloul, Sousse');
  await page.getByLabel('Instructions d’accès').fill('Appeler avant l’arrivée.');
  await page.getByLabel('Téléphone privé').fill('+21620123456');
  await page.getByLabel('Email privé').fill('client-e2e@example.invalid');
  await page.getByRole('button', { name: 'Enregistrer' }).click();
  await expect(page.getByRole('status')).toContainText('Coordonnées privées enregistrées.');

  await page.goto(`/app/projects/${project.projectId}/review`);
  await page.getByRole('button', { name: 'Soumettre pour revue DAO' }).click();

  const reviewerContext = await browser.newContext();
  const reviewer = await reviewerContext.newPage();
  await login(reviewer, e2eReviewer!);
  await reviewer.goto('/app/dao/review');
  const reviewHeading = reviewer.getByRole('heading', { name: project.title, exact: true });
  await expect(reviewHeading).toHaveCount(1);
  const reviewCard = reviewHeading.locator('xpath=../../..');
  await expect(reviewCard.getByText(project.lotTitle, { exact: true })).toBeVisible();
  await expect(reviewCard.getByText(project.lotScope, { exact: true })).toBeVisible();
  await reviewCard.getByRole('button', { name: 'Passer en revue DAO' }).click();
  await expect(reviewCard.getByText('Revue DAO', { exact: true })).toBeVisible();
  await reviewCard.getByRole('button', { name: 'Approuver' }).click();
  await expect(reviewHeading).toHaveCount(0);

  await reviewer.goto(`/app/dao/publications/new?project_id=${project.projectId}`);
  const lotLabel = reviewer.locator('label').filter({ hasText: project.lotTitle }).filter({ hasText: project.lotScope });
  const lotCheckbox = lotLabel.getByRole('checkbox');
  await expect(lotLabel).toHaveCount(1);
  await expect(lotCheckbox).toHaveCount(1);
  const publishButton = reviewer.getByRole('button', { name: 'Publier le DAO' });
  await expect(publishButton).toBeEnabled();
  await lotCheckbox.uncheck();
  await expect(reviewer.getByText('Sélectionnez au moins un lot pour publier.')).toBeVisible();
  await expect(publishButton).toBeDisabled();
  await lotCheckbox.check();
  await expect(publishButton).toBeEnabled();
  await publishButton.click();
  await expect(reviewer).toHaveURL(/\/app\/publications\/[^/]+/);
  const publicationUrl = reviewer.url();
  const publicationId = publicationUrl.split('/').pop();
  if (!publicationId) throw new Error('Publication URL did not include an ID');
  recordE2EValue(testInfo, 'publications', publicationId);
  await expect(reviewer.getByRole('heading', { name: project.title })).toBeVisible();
  await reviewerContext.close();

  const artisanContext = await browser.newContext();
  const artisan = await artisanContext.newPage();
  await login(artisan, e2eArtisan!);
  await artisan.goto('/app/artisan');
  await expect(artisan.getByText(project.title, { exact: true })).toBeVisible();
  const publicationLink = artisan.locator('a:visible').filter({ hasText: project.title });
  await expect(publicationLink).toHaveCount(1);
  await publicationLink.click();
  await expect(artisan).toHaveURL(/\/app\/artisan\/publications\//);
  const publishedLotHeading = artisan.getByRole('article').getByRole('heading', { name: project.lotTitle, exact: true });
  await expect(publishedLotHeading).toBeVisible();
  await artisan.getByLabel('Répondre à ce lot').check();
  await artisan.getByLabel('Prix proposé (TND)').fill('25000');
  await artisan.getByLabel('Délai (jours)').fill('21');
  await artisan.getByLabel('Proposition technique / inclusions').fill('Fourniture, pose, essais et remise en état.');
  await artisan.getByRole('button', { name: 'Enregistrer le brouillon' }).click();
  await expect(artisan.getByRole('status')).toContainText('Brouillon enregistré');
  await artisan.goto('/app/artisan');
  const draftCard = artisan.getByRole('link').filter({ hasText: project.title });
  await expect(draftCard.getByText('Brouillon', { exact: true })).toBeVisible();
  await draftCard.click();
  await artisan.getByRole('button', { name: 'Soumettre l’offre' }).click();
  await expect(artisan.getByRole('heading', { name: 'Offre envoyée' })).toBeVisible();
  await artisan.getByRole('button', { name: 'Préparer une nouvelle version' }).click();
  await artisan.getByLabel('Prix proposé (TND)').fill('26000');
  await artisan.getByLabel('Délai (jours)').fill('22');
  await artisan.getByLabel('Proposition technique / inclusions').fill('Version révisée avec délai actualisé.');
  await artisan.getByRole('button', { name: 'Soumettre l’offre' }).click();
  await expect(artisan.getByText(/Version 2 soumise/)).toBeVisible();
  await artisanContext.close();

  const secondArtisanContext = await browser.newContext();
  const secondArtisan = await secondArtisanContext.newPage();
  await login(secondArtisan, e2eSecondArtisan!);
  await secondArtisan.goto(`/app/artisan/publications/${publicationId}`);
  await secondArtisan.getByLabel('Répondre à ce lot').check();
  await secondArtisan.getByLabel('Prix proposé (TND)').fill('24000');
  await secondArtisan.getByLabel('Délai (jours)').fill('25');
  await secondArtisan.getByLabel('Proposition technique / inclusions').fill('Seconde offre concurrente complète.');
  await secondArtisan.getByRole('button', { name: 'Soumettre l’offre' }).click();
  await expect(secondArtisan.getByRole('heading', { name: 'Offre envoyée' })).toBeVisible();
  await secondArtisan.goto('/app/artisan/offers');
  const offerCard=secondArtisan.getByRole('heading',{name:project.title,exact:true}).locator('xpath=../..');
  await expect(offerCard.getByText('Soumise',{exact:true})).toBeVisible();
  secondArtisan.once('dialog',dialog=>dialog.accept());
  await offerCard.getByRole('button',{name:'Retirer l’offre'}).click();
  await expect(secondArtisan.getByRole('status')).toContainText('Offre retirée');
  const withdrawnCard=secondArtisan.getByRole('heading',{name:project.title,exact:true}).locator('xpath=../..');
  await expect(withdrawnCard.getByText('Retirée',{exact:true})).toBeVisible();
  await withdrawnCard.getByRole('link',{name:'Voir le DAO'}).click();
  await secondArtisan.getByRole('button',{name:'Préparer une nouvelle version'}).click();
  await secondArtisan.getByLabel('Répondre à ce lot').check();
  await secondArtisan.getByLabel('Prix proposé (TND)').fill('24000');
  await secondArtisan.getByLabel('Délai (jours)').fill('25');
  await secondArtisan.getByLabel('Proposition technique / inclusions').fill('Seconde offre concurrente complète.');
  await secondArtisan.getByRole('button', { name: 'Soumettre l’offre' }).click();
  await expect(secondArtisan.getByText(/Version 2 soumise/)).toBeVisible();
  await secondArtisanContext.close();

  await page.goto(publicationUrl);
  await expect(page.getByText(project.title)).toBeVisible();
  await expect(page.getByText('12 rue de Sahloul, Sousse', { exact: true })).toHaveCount(0);
  await expect(page.getByText('client-e2e@example.invalid', { exact: true })).toHaveCount(0);
  const comparison = page.getByRole('heading', { name: 'Comparer et attribuer les offres' }).locator('..');
  await expect(comparison.getByTestId('offer-card')).toHaveCount(2);
  await expect(comparison.getByText('Version révisée avec délai actualisé.', { exact: true })).toBeVisible();
  await expect(comparison.getByText('Fourniture, pose, essais et remise en état.', { exact: true })).toHaveCount(0);
  const selectedOffer = comparison.getByTestId('offer-card').filter({ hasText: 'Seconde offre concurrente complète.' });
  await selectedOffer.getByRole('button', { name: 'Attribuer cette offre' }).click();
  const awardResponse = page.waitForResponse(response => response.url().includes('/api/awards') && response.request().method() === 'POST');
  await selectedOffer.getByRole('button', { name: 'Confirmer l’attribution' }).click();
  expect((await awardResponse).ok()).toBeTruthy();
  await expect(comparison.getByRole('status')).toContainText('Aucun contrat');
  await expect(comparison.getByText('Lot attribué', { exact: true })).toBeVisible();
  await expect(selectedOffer.getByText(/Offre retenue/)).toBeVisible();

  const requests = await adminRows('project_requests', `project_id=eq.${project.projectId}&select=id,status`);
  expect(requests).toEqual([{ id: expect.any(String), status: 'awarded' }]);
  const awards = await adminRows('award_items', `project_id=eq.${project.projectId}&active=eq.true&select=id,request_id,bid_item_id,agreed_millimes`);
  expect(awards).toHaveLength(1);
  expect(awards[0]).toEqual(expect.objectContaining({ request_id: requests[0].id, agreed_millimes: 24000000 }));
  expect(await adminRows('contracts', `project_id=eq.${project.projectId}&select=id`)).toHaveLength(0);
  const nonSelected = comparison.getByTestId('offer-card').filter({ hasText: 'Version révisée avec délai actualisé.' });
  await expect(nonSelected.getByText('Non retenue', { exact: true })).toBeVisible();
  const artisanCheckContext = await browser.newContext();
  const artisanCheck = await artisanCheckContext.newPage();
  await login(artisanCheck, e2eArtisan!);
  await artisanCheck.goto(`/app/artisan/publications/${publicationId}`);
  await expect(artisanCheck.getByText('Non retenue', { exact: true })).toBeVisible();
  await expect(artisanCheck.getByText('Lot fermé aux nouvelles offres')).toBeVisible();
  await expect(artisanCheck.getByRole('button', { name: 'Préparer une nouvelle version' })).toHaveCount(0);
  await artisanCheckContext.close();

  await comparison.getByRole('button', { name: 'Annuler l’attribution', exact: true }).click();
  const cancellation = comparison.getByRole('group', { name: 'Annulation de l’attribution' });
  await expect(cancellation.getByRole('button', { name: 'Confirmer l’annulation' })).toBeDisabled();
  await cancellation.getByLabel('Motif d’annulation').selectOption('other');
  await expect(cancellation.getByRole('button', { name: 'Confirmer l’annulation' })).toBeDisabled();
  await cancellation.getByLabel('Commentaire').fill('Désaccord documenté E2E');
  const cancelResponse = page.waitForResponse(response => response.url().endsWith('/api/awards/cancel') && response.request().method() === 'POST');
  await cancellation.getByRole('button', { name: 'Confirmer l’annulation' }).click();
  expect((await cancelResponse).ok()).toBeTruthy();
  await expect(comparison.getByRole('status')).toContainText('de nouveau ouverts');
  await expect(comparison.getByText('Lot attribué', { exact: true })).toHaveCount(0);
  await expect(comparison.getByText(/Désaccord documenté E2E/)).toBeVisible();
  await nonSelected.getByRole('button', { name: 'Attribuer cette offre' }).click();
  const reassignment = page.waitForResponse(response => response.url().endsWith('/api/awards') && response.request().method() === 'POST');
  await nonSelected.getByRole('button', { name: 'Confirmer l’attribution' }).click();
  expect((await reassignment).ok()).toBeTruthy();
  await expect(nonSelected.getByText(/Offre retenue/)).toBeVisible();
  await expect(selectedOffer.getByText('Non retenue', { exact: true })).toBeVisible();
  const history = await adminRows('award_items', `project_id=eq.${project.projectId}&select=id,active,agreed_millimes`);
  expect(history).toHaveLength(2);
  expect(history.filter(row => row.active)).toHaveLength(1);
  expect(history.find(row => row.id === awards[0].id)).toEqual(expect.objectContaining({ active: false, agreed_millimes: 24000000 }));
  const cancelAudit = await adminRows('award_cancellations', `award_item_id=eq.${awards[0].id}&select=actor_id,created_at,reason,comment`);
  expect(cancelAudit).toEqual([{ actor_id: expect.any(String), created_at: expect.any(String), reason: 'other', comment: 'Désaccord documenté E2E' }]);

});
