import { test, expect, type Browser, type Page } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';

async function login(page:Page,email:string,password:string){await page.goto('/auth/login');await page.getByPlaceholder('Votre email').fill(email);await page.getByPlaceholder('Mot de passe').fill(password);await page.getByRole('button',{name:'Se connecter'}).click();await expect(page).toHaveURL(/\/app\/projects/);}
function rememberProject(id:string){const file=process.env.DAO_E2E_STATE_FILE;if(!file)return;const state=JSON.parse(readFileSync(file,'utf8'));state.projects=[...(state.projects||[]),id];writeFileSync(file,JSON.stringify(state));}
test('Client → reviewer DAO → publication DEV',async({browser},testInfo)=>{
 const clientEmail=process.env.PLAYWRIGHT_CLIENT_EMAIL,clientPassword=process.env.PLAYWRIGHT_CLIENT_PASSWORD,reviewerEmail=process.env.PLAYWRIGHT_REVIEWER_EMAIL,reviewerPassword=process.env.PLAYWRIGHT_REVIEWER_PASSWORD;
 test.skip(!clientEmail||!clientPassword||!reviewerEmail||!reviewerPassword,'E2E users were not provisioned');
 const clientContext=await browser.newContext();const client=await clientContext.newPage();await login(client,clientEmail!,clientPassword!);
 const projectTitle=`DAO E2E DEV ${testInfo.project.name}`;
 await client.goto('/app/projects/new');await client.getByLabel('Titre du projet').fill(projectTitle);await client.getByLabel('Description').fill('Projet E2E client reviewer publication');await client.getByLabel('Gouvernorat').selectOption({index:1});await client.getByLabel('Délégation').selectOption({index:1});await client.getByLabel('Localité').selectOption({index:1});await client.getByLabel('Budget indicatif (TND)').fill('150000');await client.getByRole('button',{name:'Créer le projet et ajouter les demandes'}).click();await expect(client).toHaveURL(/\/app\/projects\/(?!new(?:\/|$))[^/?#]+/);const projectId=client.url().split('/').pop()!;rememberProject(projectId);
 await client.getByLabel('Métier').selectOption({index:1});await client.getByLabel('Intitulé').fill('Lot plomberie E2E');await client.getByLabel('Budget indicatif du lot (TND)').fill('25000');await client.getByLabel('Périmètre des travaux').fill('Installation plomberie complète');await client.getByRole('button',{name:'Ajouter la demande'}).click();await expect(client.getByText('Lot plomberie E2E')).toBeVisible();
 await client.getByRole('link',{name:'Revoir le DAO'}).click();await client.getByRole('button',{name:'Soumettre pour revue DAO'}).click();await expect(client.getByText('Validation client')).toBeVisible();await client.close();await clientContext.close();
 const reviewerContext=await browser.newContext();const reviewer=await reviewerContext.newPage();await login(reviewer,reviewerEmail!,reviewerPassword!);await reviewer.goto('/app/dao/review');await expect(reviewer.getByText(projectTitle)).toBeVisible();await reviewer.getByLabel('Commentaire de revue').fill('Commentaire E2E DAO');await reviewer.getByRole('button',{name:'Passer en revue DAO'}).click();await expect(reviewer.getByText('dao_review')).toBeVisible();await reviewer.getByLabel('Commentaire de revue').fill('Validation finale E2E');await reviewer.getByRole('button',{name:'Approuver'}).click();
 await reviewer.goto(`/app/dao/publications/new?project_id=${projectId}`);await reviewer.getByRole('button',{name:'Publier le DAO'}).click();await expect(reviewer).toHaveURL(/\/app\/publications\/[^/]+/);const publicationUrl=reviewer.url();const publicationId=publicationUrl.split('/').pop()!;const stateFile=process.env.DAO_E2E_STATE_FILE!;const state=JSON.parse(readFileSync(stateFile,'utf8'));state.publications=[...(state.publications||[]),publicationId];writeFileSync(stateFile,JSON.stringify(state));await expect(reviewer.getByText(projectTitle)).toBeVisible();await reviewer.screenshot({path:`test-results/${testInfo.project.name}-published.png`,fullPage:true});await reviewerContext.close();
 const finalContext=await browser.newContext();const final=await finalContext.newPage();await login(final,clientEmail!,clientPassword!);await final.goto(publicationUrl);await expect(final.getByText(projectTitle)).toBeVisible();await finalContext.close();
});
