'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { supabaseBrowser } from '../../../../lib/supabase-browser';
import { Badge, Button, Card, Input } from '../../../../components/ui';
import { statusLabel } from '../../../../lib/utils';

export default function ProjectDetail() {
  const { id } = useParams<{ id: string }>();
  const [project, setProject] = useState<any>(); const [requests, setRequests] = useState<any[]>([]);
  const [trade, setTrade] = useState(''); const [title, setTitle] = useState(''); const [scope, setScope] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  async function load() { setLoading(true); const supabase = supabaseBrowser(); const projectResult = await supabase.from('projects').select('*').eq('id', id).single(); const requestsResult = await supabase.from('project_requests').select('id,status').eq('project_id', id); if (projectResult.error || requestsResult.error) setError('Projet inaccessible ou introuvable.'); setProject(projectResult.data); setRequests(requestsResult.data ?? []); setLoading(false); }
  useEffect(() => { void load(); }, [id]);
  async function addRequest(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); setSuccess(''); const { data: sessionData } = await supabaseBrowser().auth.getSession(); const session = sessionData.session; if (!session) { setError('Session expirée.'); setSaving(false); return; } const response = await fetch('/api/projects/requests', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ project_id: id, trade_id: trade, title, scope }) }); const { data, error: responseError } = await response.json(); if (!response.ok || !data) { setError(responseError || 'Ajout refusé.'); setSaving(false); return; } setTrade(''); setTitle(''); setScope(''); setSuccess('Demande ajoutée.'); await load(); setSaving(false); }
  if (loading) return <p>Chargement…</p>; if (!project) return <p role="alert">Projet inaccessible ou introuvable.</p>;
  return <section><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-teal">Préparation du projet</p><h1 className="mt-1 text-3xl font-bold">{project.project_type} · {project.surface_m2 ?? '—'} m²</h1></div><Badge>{statusLabel[project.status] ?? project.status}</Badge></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card><h2 className="font-semibold">Demandes de travaux</h2>{requests.length === 0 ? <p className="mt-5 text-sm text-black/50">Aucune demande enregistrée.</p> : <div className="mt-4 space-y-3">{requests.map((request, index) => <div key={request.id} className="flex justify-between rounded-xl bg-sand p-3 text-sm"><span>Demande {index + 1}</span><Badge>{statusLabel[request.status] ?? request.status}</Badge></div>)}</div>}</Card><Card><h2 className="font-semibold">Ajouter une demande</h2><form onSubmit={addRequest} className="mt-4 space-y-3"><Input placeholder="Métier / trade UUID" value={trade} onChange={(event) => setTrade(event.target.value)} required /><Input placeholder="Ex. Plomberie complète" value={title} onChange={(event) => setTitle(event.target.value)} required /><Input placeholder="Décrivez le périmètre" value={scope} onChange={(event) => setScope(event.target.value)} required />{error && <p className="text-xs text-red-600" role="alert">{error}</p>}{success && <p className="text-xs text-teal" role="status">{success}</p>}<Button className="w-full" disabled={saving}>{saving ? 'Ajout…' : 'Ajouter la demande'}</Button></form></Card></div></section>;
}
