'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { supabaseBrowser } from '../../../lib/supabase-browser';
import { Badge, Button, Card, SectionHeading } from '../../../components/ui';

type Invitation={id:string;project_id:string;expected_role:'client'|'contractor';recipient_name:string|null;status:string;created_at:string;expires_at:string;project_title:string;principal_request_id:string|null;lot_title:string|null};
const labels:Record<string,string>={pending:'À traiter',accepted:'Acceptée',declined:'Refusée',revoked:'Révoquée',expired:'Expirée'};
const tones:Record<string,'neutral'|'teal'|'clay'|'red'>={pending:'clay',accepted:'teal',declined:'neutral',revoked:'red',expired:'red'};
export default function Invitations(){
  const [rows,setRows]=useState<Invitation[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function load(){setLoading(true);const {data,error:rpcError}=await supabaseBrowser().rpc('my_project_invitations');if(rpcError)setError('Impossible de charger vos invitations.');else setRows((data??[]) as Invitation[]);setLoading(false)}
  useEffect(()=>{void load()},[]);const pending=useMemo(()=>rows.filter(r=>r.status==='pending'),[rows]);const history=useMemo(()=>rows.filter(r=>r.status!=='pending'),[rows]);
  async function respond(row:Invitation,accept:boolean){setBusy(row.id);setError('');setMessage('');const {data,error:rpcError}=await supabaseBrowser().rpc('respond_my_project_invitation',{p_invitation_id:row.id,p_accept:accept});if(rpcError)setError(rpcError.message||'Cette invitation ne peut plus être traitée.');else{setMessage(accept?'Invitation acceptée. Le chantier est maintenant disponible.':'Invitation refusée.');await load();if(accept&&data)window.location.assign(`/app/projects/${data}`)}setBusy('')}
  const list=(items:Invitation[])=><div className="space-y-3">{items.map(row=><Card key={row.id}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex flex-wrap gap-2"><Badge tone={tones[row.status]??'neutral'}>{labels[row.status]??row.status}</Badge><Badge>{row.expected_role==='contractor'?'Invitation artisan':'Invitation client'}</Badge></div><h2 className="mt-3 text-lg font-bold">{row.project_title}</h2>{row.lot_title&&<p className="mt-1 text-sm text-black/60">Lot : {row.lot_title}</p>}<p className="mt-2 text-xs text-black/45">Reçue le {new Date(row.created_at).toLocaleDateString('fr-TN')} · expire le {new Date(row.expires_at).toLocaleDateString('fr-TN')}</p></div>{row.status==='pending'?<div className="flex gap-2"><Button disabled={busy===row.id} onClick={()=>void respond(row,true)}>Accepter</Button><Button disabled={busy===row.id} className="bg-white text-red-700 ring-1 ring-red-200 hover:bg-red-50" onClick={()=>void respond(row,false)}>Refuser</Button></div>:row.status==='accepted'?<Link href={`/app/projects/${row.project_id}`} className="inline-flex min-h-10 items-center rounded-xl border border-black/10 px-4 py-2 text-sm font-semibold">Voir le chantier</Link>:null}</div></Card>)}</div>;
  if(loading)return <p>Chargement de vos invitations…</p>;
  return <section className="space-y-6"><SectionHeading eyebrow="Mon compte" title="Mes invitations" description="Retrouvez et traitez les invitations envoyées à l’adresse confirmée de votre compte."/>{error&&<p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="rounded-xl bg-teal/10 px-4 py-3 text-sm text-teal">{message}</p>}<div><h2 className="mb-3 text-lg font-bold">À traiter</h2>{pending.length?list(pending):<Card className="border-dashed"><p className="text-sm text-black/55">Aucune invitation en attente.</p></Card>}</div>{history.length>0&&<div><h2 className="mb-3 text-lg font-bold">Historique</h2>{list(history)}</div>}</section>
}
