-- D.A.O MVP / proposition pour revue, Supabase PostgreSQL 15+ / base neuve seulement.
begin;
create table public.governorates (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), code text not null unique, name_fr text not null, name_ar text not null);
create table public.delegations (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), governorate_id uuid not null references public.governorates, code text not null unique, name_fr text not null, name_ar text not null, unique(id,governorate_id));
create table public.localities (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), delegation_id uuid not null references public.delegations, name_fr text not null, name_ar text, unique(id,delegation_id));
create table public.trades (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), code text not null unique, name_fr text not null, name_ar text, active boolean not null default true);
create table public.profiles (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), user_id uuid not null unique references auth.users, display_name text not null);
create table public.profile_contacts (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), user_id uuid not null unique references auth.users, phone_e164 text check(phone_e164 ~ '^\+216[0-9]{8}$'), contact_email text);
create table public.user_roles (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), user_id uuid not null references auth.users, role text not null check(role in ('client','contractor','dao_reviewer','dao_admin')), unique(user_id,role));
create table public.contractor_profiles (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), user_id uuid not null unique references auth.users, business_name text not null, verification_status text not null default 'pending' check(verification_status in ('pending','verified','rejected','suspended')), contractor_type text not null default 'artisan' check(contractor_type in ('artisan','company','general_contractor','independent_professional')), public_presentation text not null default '', years_experience integer check(years_experience between 0 and 100), availability text not null default 'to_discuss' check(availability in ('available','scheduled','unavailable','to_discuss')), available_from date, public_trade_name text not null default '', public_slug text unique, public_identity_status text not null default 'draft' check(public_identity_status in ('draft','approved','hidden')));
create table public.contractor_trades (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), contractor_id uuid not null references public.contractor_profiles, trade_id uuid not null references public.trades, unique(contractor_id,trade_id));
create table public.contractor_service_areas (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), contractor_id uuid not null references public.contractor_profiles, governorate_id uuid not null references public.governorates, delegation_id uuid, foreign key(delegation_id,governorate_id) references public.delegations(id,governorate_id), unique nulls not distinct(contractor_id,governorate_id,delegation_id));
create table public.projects (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), client_id uuid not null references auth.users, currency text not null default 'TND' check(currency='TND'), status text not null default 'draft' check(status in ('draft','open','closed','archived')), project_type text not null default 'other' check(project_type in ('construction','renovation','repair','extension','other')), surface_m2 numeric(12,2) check(surface_m2>0), desired_start_date date, indicative_budget_millimes bigint check(indicative_budget_millimes>=0));
create table public.project_private_details (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null unique references public.projects, exact_address text, access_instructions text, contact_phone text check(contact_phone ~ '^\+216[0-9]{8}$'), contact_email text);
create table public.project_versions (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, version_no integer not null check(version_no>0), title text not null, description text not null, governorate_id uuid not null references public.governorates, delegation_id uuid, locality_id uuid, status text not null default 'draft' check(status in ('draft','client_review','dao_review','approved','rejected')), foreign key(delegation_id,governorate_id) references public.delegations(id,governorate_id), foreign key(locality_id,delegation_id) references public.localities(id,delegation_id), check(locality_id is null or delegation_id is not null), unique(project_id,version_no), unique(id,project_id), project_type text not null default 'other' check(project_type in ('construction','renovation','repair','extension','other')), surface_m2 numeric(12,2) check(surface_m2>0), desired_start_date date, indicative_budget_millimes bigint check(indicative_budget_millimes>=0));
create table public.project_requests (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, status text not null default 'open' check(status in ('open','reserved','awarded','contracted','withdrawn')), unique(id,project_id));
create table public.project_request_versions (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), request_id uuid not null, project_id uuid not null, version_no integer not null check(version_no>0), trade_id uuid not null references public.trades, title text not null, scope text not null, budget_millimes bigint check(budget_millimes>=0), foreign key(request_id,project_id) references public.project_requests(id,project_id), unique(request_id,version_no), unique(id,project_id), unique(id,project_id,request_id));
create table public.project_version_requests (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, project_version_id uuid not null, request_version_id uuid not null, foreign key(project_version_id,project_id) references public.project_versions(id,project_id), foreign key(request_version_id,project_id) references public.project_request_versions(id,project_id), unique(project_version_id,request_version_id));
create table public.project_reviews (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_version_id uuid not null references public.project_versions, actor_id uuid not null references auth.users, actor_role text not null check(actor_role in ('client','dao')), decision text not null check(decision in ('approved','changes_requested','rejected')), reason text);
create table public.publications (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, project_version_id uuid not null, visibility text not null check(visibility in ('public','targeted','invite_only')), status text not null default 'published' check(status in ('published','suspended','closed','superseded')), safe_title text not null, safe_description text not null, governorate_id uuid not null references public.governorates, delegation_id uuid, foreign key(delegation_id,governorate_id) references public.delegations(id,governorate_id), foreign key(project_version_id,project_id) references public.project_versions(id,project_id), project_type text not null default 'other' check(project_type in ('construction','renovation','repair','extension','other')), surface_m2 numeric(12,2) check(surface_m2>0), desired_start_date date, indicative_budget_millimes bigint check(indicative_budget_millimes>=0), published_at timestamptz not null default now(), submission_deadline timestamptz, closed_at timestamptz, check(submission_deadline is null or submission_deadline>published_at), check(closed_at is null or closed_at>=published_at), check((status='closed')=(closed_at is not null)));
create table public.publication_requests (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), publication_id uuid not null references public.publications, request_version_id uuid not null references public.project_request_versions, trade_id uuid not null references public.trades, safe_title text not null, safe_scope text not null, unique(publication_id,request_version_id));
create table public.publication_recipients (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), publication_id uuid not null references public.publications, contractor_id uuid not null references public.contractor_profiles, source text not null check(source in ('targeted','invitation')), revoked_at timestamptz, unique(publication_id,contractor_id));
create table public.ai_runs (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, status text not null check(status in ('queued','running','succeeded','failed')), provider text not null, model text, raw_result jsonb, error_code text);
create table public.ai_proposals (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), run_id uuid not null references public.ai_runs, trade_id uuid references public.trades, proposed_scope text not null, status text not null check(status in ('proposed','accepted','rejected','needs_mapping')), check(trade_id is not null or status in ('needs_mapping','rejected')));
create table public.bids (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, contractor_id uuid not null references public.contractor_profiles, unique(project_id,contractor_id), unique(id,project_id), unique(id,project_id,contractor_id));
create table public.bid_versions (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), bid_id uuid not null, project_id uuid not null, version_no integer not null check(version_no>0), status text not null default 'draft' check(status in ('draft','submitted','withdrawn','expired','superseded')), validity text not null default 'current' check(validity in ('current','reconfirmation_required','obsolete')), expires_at timestamptz not null, foreign key(bid_id,project_id) references public.bids(id,project_id), unique(bid_id,version_no), unique(id,project_id), contractor_id uuid not null references public.contractor_profiles, submitted_at timestamptz, foreign key(bid_id,project_id,contractor_id) references public.bids(id,project_id,contractor_id), unique(id,project_id,contractor_id), check(status<>'submitted' or submitted_at is not null), check(status<>'draft' or submitted_at is null));
create table public.bid_items (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), bid_version_id uuid not null, project_id uuid not null, request_version_id uuid not null, price_millimes bigint not null check(price_millimes>=0), duration_days integer not null check(duration_days>0), inclusions text not null, exclusions text, foreign key(bid_version_id,project_id) references public.bid_versions(id,project_id), foreign key(request_version_id,project_id) references public.project_request_versions(id,project_id), unique(bid_version_id,request_version_id), unique(id,bid_version_id), contractor_id uuid not null references public.contractor_profiles, request_id uuid not null, foreign key(bid_version_id,project_id,contractor_id) references public.bid_versions(id,project_id,contractor_id), foreign key(request_version_id,project_id,request_id) references public.project_request_versions(id,project_id,request_id), unique(id,project_id,contractor_id,request_id));
create table public.bid_groups (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), bid_version_id uuid not null references public.bid_versions, indivisible boolean not null default false, discount_millimes bigint not null default 0 check(discount_millimes>=0), unique(id,bid_version_id));
create table public.bid_group_items (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), group_id uuid not null, bid_version_id uuid not null, bid_item_id uuid not null, foreign key(group_id,bid_version_id) references public.bid_groups(id,bid_version_id), foreign key(bid_item_id,bid_version_id) references public.bid_items(id,bid_version_id), unique(bid_item_id));
create table public.awards (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, contractor_id uuid not null references public.contractor_profiles, status text not null default 'confirmed' check(status in ('confirmed','contracting','contracted','cancelled')), unique(id,project_id), unique(id,project_id,contractor_id));
create table public.award_items (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), award_id uuid not null, project_id uuid not null, request_id uuid not null, bid_item_id uuid not null references public.bid_items, agreed_millimes bigint not null check(agreed_millimes>=0), active boolean not null default true, foreign key(award_id,project_id) references public.awards(id,project_id), foreign key(request_id,project_id) references public.project_requests(id,project_id), unique(award_id,request_id), contractor_id uuid not null references public.contractor_profiles, foreign key(award_id,project_id,contractor_id) references public.awards(id,project_id,contractor_id), foreign key(bid_item_id,project_id,contractor_id,request_id) references public.bid_items(id,project_id,contractor_id,request_id));
create table public.contracts (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), award_id uuid not null unique references public.awards, project_id uuid not null references public.projects, status text not null default 'draft' check(status in ('draft','review','ready')), unique(id,project_id), foreign key(award_id,project_id) references public.awards(id,project_id));
create table public.contract_versions (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), contract_id uuid not null references public.contracts, version_no integer not null check(version_no>0), content jsonb not null, content_hash text not null, unique(contract_id,version_no));
create table public.contract_parties (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), contract_id uuid not null references public.contracts, role text not null check(role in ('client','contractor','dao')), user_id uuid references auth.users, legal_name text not null, unique(contract_id,role));
create table public.conversations (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, contractor_id uuid not null references public.contractor_profiles, unique(project_id,contractor_id));
create table public.conversation_participants (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), conversation_id uuid not null references public.conversations, user_id uuid not null references auth.users, unique(conversation_id,user_id));
create table public.messages (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), conversation_id uuid not null references public.conversations, author_id uuid not null references auth.users, body text not null check(length(body) between 1 and 10000));
create table public.documents (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), project_id uuid not null references public.projects, owner_id uuid not null references auth.users, object_path text not null unique, original_name text not null, mime_type text not null, size_bytes bigint not null check(size_bytes between 1 and 20971520), status text not null default 'quarantined' check(status in ('quarantined','approved','rejected')));
create table public.document_grants (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), document_id uuid not null references public.documents, user_id uuid not null references auth.users, revoked_at timestamptz, unique(document_id,user_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), user_id uuid not null references auth.users, kind text not null, payload jsonb not null default '{}'::jsonb, read_at timestamptz);
create table public.audit_events (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), actor_id uuid references auth.users, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb);
create table public.command_receipts (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), actor_id uuid not null references auth.users, idempotency_key text not null, command text not null, result jsonb not null, unique(actor_id,idempotency_key));
create table public.portfolio_projects (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), contractor_id uuid not null references public.contractor_profiles, title text not null, description text not null, completed_year integer check(completed_year between 1900 and 2200), governorate_id uuid references public.governorates, status text not null default 'draft' check(status in ('draft','pending_review','published','hidden')), unique(id,contractor_id));
create table public.portfolio_assets (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), portfolio_project_id uuid not null, contractor_id uuid not null, object_path text not null unique, caption text, sort_order integer not null default 0 check(sort_order>=0), mime_type text not null check(mime_type in ('image/jpeg','image/png','image/webp')), size_bytes bigint not null check(size_bytes between 1 and 20971520), status text not null default 'quarantined' check(status in ('quarantined','approved','rejected')), foreign key(portfolio_project_id,contractor_id) references public.portfolio_projects(id,contractor_id));
create table public.bid_documents (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), bid_version_id uuid not null, project_id uuid not null, contractor_id uuid not null, object_path text not null unique, original_name text not null, mime_type text not null, size_bytes bigint not null check(size_bytes between 1 and 20971520), status text not null default 'quarantined' check(status in ('quarantined','approved','rejected')), foreign key(bid_version_id,project_id,contractor_id) references public.bid_versions(id,project_id,contractor_id));
create unique index one_active_award_per_request on public.award_items(request_id) where active;
create unique index one_live_publication on public.publications(project_id) where status in ('published','suspended');
create index on public.delegations(governorate_id);
create index on public.localities(delegation_id);
create index on public.profiles(user_id);
create index on public.profile_contacts(user_id);
create index on public.user_roles(user_id);
create index on public.contractor_profiles(user_id);
create index on public.contractor_trades(contractor_id);
create index on public.contractor_trades(trade_id);
create index on public.contractor_service_areas(contractor_id);
create index on public.contractor_service_areas(governorate_id);
create index on public.contractor_service_areas(delegation_id);
create index on public.projects(client_id);
create index on public.project_private_details(project_id);
create index on public.project_versions(project_id);
create index on public.project_versions(governorate_id);
create index on public.project_versions(delegation_id);
create index on public.project_versions(locality_id);
create index on public.project_requests(project_id);
create index on public.project_request_versions(request_id);
create index on public.project_request_versions(project_id);
create index on public.project_request_versions(trade_id);
create index on public.project_version_requests(project_id);
create index on public.project_version_requests(project_version_id);
create index on public.project_version_requests(request_version_id);
create index on public.project_reviews(project_version_id);
create index on public.project_reviews(actor_id);
create index on public.publications(project_id);
create index on public.publications(project_version_id);
create index on public.publications(governorate_id);
create index on public.publications(delegation_id);
create index on public.publication_requests(publication_id);
create index on public.publication_requests(request_version_id);
create index on public.publication_requests(trade_id);
create index on public.publication_recipients(publication_id);
create index on public.publication_recipients(contractor_id);
create index on public.ai_runs(project_id);
create index on public.ai_proposals(run_id);
create index on public.ai_proposals(trade_id);
create index on public.bids(project_id);
create index on public.bids(contractor_id);
create index on public.bid_versions(bid_id);
create index on public.bid_versions(project_id);
create index on public.bid_versions(contractor_id);
create index on public.bid_items(bid_version_id);
create index on public.bid_items(project_id);
create index on public.bid_items(request_version_id);
create index on public.bid_items(contractor_id);
create index on public.bid_items(request_id);
create index on public.bid_groups(bid_version_id);
create index on public.bid_group_items(group_id);
create index on public.bid_group_items(bid_version_id);
create index on public.bid_group_items(bid_item_id);
create index on public.awards(project_id);
create index on public.awards(contractor_id);
create index on public.award_items(award_id);
create index on public.award_items(project_id);
create index on public.award_items(request_id);
create index on public.award_items(bid_item_id);
create index on public.award_items(contractor_id);
create index on public.contracts(award_id);
create index on public.contracts(project_id);
create index on public.contract_versions(contract_id);
create index on public.contract_parties(contract_id);
create index on public.contract_parties(user_id);
create index on public.conversations(project_id);
create index on public.conversations(contractor_id);
create index on public.conversation_participants(conversation_id);
create index on public.conversation_participants(user_id);
create index on public.messages(conversation_id);
create index on public.messages(author_id);
create index on public.documents(project_id);
create index on public.documents(owner_id);
create index on public.document_grants(document_id);
create index on public.document_grants(user_id);
create index on public.notifications(user_id);
create index on public.audit_events(actor_id);
create index on public.audit_events(entity_id);
create index on public.command_receipts(actor_id);
create index on public.portfolio_projects(contractor_id);
create index on public.portfolio_projects(governorate_id);
create index on public.portfolio_assets(portfolio_project_id);
create index on public.portfolio_assets(contractor_id);
create index on public.bid_documents(bid_version_id);
create index on public.bid_documents(project_id);
create index on public.bid_documents(contractor_id);
commit;
