-- Lecture sous JWT utilisateur ; aucune écriture directe par anon/authenticated.
begin;
create schema if not exists dao_private;
revoke all on schema dao_private from public;
grant usage on schema dao_private to anon, authenticated;
create function dao_private.staff() returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.user_roles where user_id=auth.uid() and role in ('dao_admin','dao_reviewer'));
$$;
create function dao_private.owner(p uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.projects where id=p and client_id=auth.uid());
$$;
create function dao_private.pro(c uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.contractor_profiles where id=c and user_id=auth.uid());
$$;
create function dao_private.bid(b uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.bids x where x.id=b and (dao_private.pro(x.contractor_id) or (dao_private.owner(x.project_id) and exists(select 1 from public.bid_versions v where v.bid_id=x.id and v.submitted_at is not null))));
$$;
create function dao_private.conversation(c uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.conversation_participants where conversation_id=c and user_id=auth.uid());
$$;
create function dao_private.contract(c uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.contract_parties where contract_id=c and user_id=auth.uid());
$$;
create function dao_private.publication(p uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.publications x where x.id=p and (
 dao_private.staff() or dao_private.owner(x.project_id) or (x.status='published' and (
 x.visibility='public' or exists(select 1 from public.publication_recipients r join public.contractor_profiles c on c.id=r.contractor_id
 where r.publication_id=x.id and r.revoked_at is null and c.user_id=auth.uid() and c.verification_status='verified'
 and ((x.visibility='targeted' and r.source='targeted') or (x.visibility='invite_only' and r.source='invitation')))))));
$$;
create function dao_private.bid_version(v uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.bid_versions x join public.bids b on b.id=x.bid_id
 where x.id=v and (dao_private.staff() or dao_private.pro(b.contractor_id) or (x.submitted_at is not null and dao_private.owner(b.project_id))));
$$;
create function dao_private.project_version(v uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.project_versions x where x.id=v and (dao_private.staff() or dao_private.owner(x.project_id)));
$$;
create function dao_private.ai_run(r uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.ai_runs x where x.id=r and (dao_private.staff() or dao_private.owner(x.project_id)));
$$;
create function dao_private.award(a uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.awards x where x.id=a and (dao_private.staff() or dao_private.owner(x.project_id) or dao_private.pro(x.contractor_id)));
$$;
create function dao_private.portfolio(p uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.portfolio_projects x join public.contractor_profiles c on c.id=x.contractor_id
 where x.id=p and (dao_private.staff() or dao_private.pro(x.contractor_id) or (x.status='published' and c.verification_status='verified' and c.public_identity_status='approved')));
$$;
revoke all on all functions in schema dao_private from public;
grant execute on all functions in schema dao_private to anon,authenticated;

alter table public.governorates enable row level security;
revoke all on public.governorates from anon,authenticated;
grant select on public.governorates to authenticated;
grant all on public.governorates to service_role;
grant select on public.governorates to anon;
create policy read_allowed on public.governorates for select to anon,authenticated using (dao_private.staff() or (true));
alter table public.delegations enable row level security;
revoke all on public.delegations from anon,authenticated;
grant select on public.delegations to authenticated;
grant all on public.delegations to service_role;
grant select on public.delegations to anon;
create policy read_allowed on public.delegations for select to anon,authenticated using (dao_private.staff() or (true));
alter table public.localities enable row level security;
revoke all on public.localities from anon,authenticated;
grant select on public.localities to authenticated;
grant all on public.localities to service_role;
grant select on public.localities to anon;
create policy read_allowed on public.localities for select to anon,authenticated using (dao_private.staff() or (true));
alter table public.trades enable row level security;
revoke all on public.trades from anon,authenticated;
grant select on public.trades to authenticated;
grant all on public.trades to service_role;
grant select on public.trades to anon;
create policy read_allowed on public.trades for select to anon,authenticated using (dao_private.staff() or (active));
alter table public.profiles enable row level security;
revoke all on public.profiles from anon,authenticated;
grant select on public.profiles to authenticated;
grant all on public.profiles to service_role;
create policy read_allowed on public.profiles for select to authenticated using (dao_private.staff() or (user_id=auth.uid()));
alter table public.profile_contacts enable row level security;
revoke all on public.profile_contacts from anon,authenticated;
grant select on public.profile_contacts to authenticated;
grant all on public.profile_contacts to service_role;
create policy read_allowed on public.profile_contacts for select to authenticated using (dao_private.staff() or (user_id=auth.uid()));
alter table public.user_roles enable row level security;
revoke all on public.user_roles from anon,authenticated;
grant select on public.user_roles to authenticated;
grant all on public.user_roles to service_role;
create policy read_allowed on public.user_roles for select to authenticated using (dao_private.staff() or (user_id=auth.uid()));
alter table public.contractor_profiles enable row level security;
revoke all on public.contractor_profiles from anon,authenticated;
grant select on public.contractor_profiles to authenticated;
grant all on public.contractor_profiles to service_role;
create policy read_allowed on public.contractor_profiles for select to authenticated using (dao_private.staff() or (user_id=auth.uid()));
alter table public.contractor_trades enable row level security;
revoke all on public.contractor_trades from anon,authenticated;
grant select on public.contractor_trades to authenticated;
grant all on public.contractor_trades to service_role;
create policy read_allowed on public.contractor_trades for select to authenticated using (dao_private.staff() or (dao_private.pro(contractor_id)));
alter table public.contractor_service_areas enable row level security;
revoke all on public.contractor_service_areas from anon,authenticated;
grant select on public.contractor_service_areas to authenticated;
grant all on public.contractor_service_areas to service_role;
create policy read_allowed on public.contractor_service_areas for select to authenticated using (dao_private.staff() or (dao_private.pro(contractor_id)));
alter table public.projects enable row level security;
revoke all on public.projects from anon,authenticated;
grant select on public.projects to authenticated;
grant all on public.projects to service_role;
create policy read_allowed on public.projects for select to authenticated using (dao_private.staff() or (client_id=auth.uid()));
alter table public.project_private_details enable row level security;
revoke all on public.project_private_details from anon,authenticated;
grant select on public.project_private_details to authenticated;
grant all on public.project_private_details to service_role;
create policy read_allowed on public.project_private_details for select to authenticated using (dao_private.staff() or (dao_private.owner(project_id)));
alter table public.project_versions enable row level security;
revoke all on public.project_versions from anon,authenticated;
grant select on public.project_versions to authenticated;
grant all on public.project_versions to service_role;
create policy read_allowed on public.project_versions for select to authenticated using (dao_private.staff() or (dao_private.owner(project_id)));
alter table public.project_requests enable row level security;
revoke all on public.project_requests from anon,authenticated;
grant select on public.project_requests to authenticated;
grant all on public.project_requests to service_role;
create policy read_allowed on public.project_requests for select to authenticated using (dao_private.staff() or (dao_private.owner(project_id)));
alter table public.project_request_versions enable row level security;
revoke all on public.project_request_versions from anon,authenticated;
grant select on public.project_request_versions to authenticated;
grant all on public.project_request_versions to service_role;
create policy read_allowed on public.project_request_versions for select to authenticated using (dao_private.staff() or (dao_private.owner(project_id)));
alter table public.project_version_requests enable row level security;
revoke all on public.project_version_requests from anon,authenticated;
grant select on public.project_version_requests to authenticated;
grant all on public.project_version_requests to service_role;
create policy read_allowed on public.project_version_requests for select to authenticated using (dao_private.staff() or (dao_private.owner(project_id)));
alter table public.project_reviews enable row level security;
revoke all on public.project_reviews from anon,authenticated;
grant select on public.project_reviews to authenticated;
grant all on public.project_reviews to service_role;
create policy read_allowed on public.project_reviews for select to authenticated using (dao_private.staff() or (dao_private.project_version(project_version_id)));
alter table public.publications enable row level security;
revoke all on public.publications from anon,authenticated;
grant select on public.publications to authenticated;
grant all on public.publications to service_role;
grant select on public.publications to anon;
create policy read_allowed on public.publications for select to anon,authenticated using (dao_private.staff() or (dao_private.publication(id)));
alter table public.publication_requests enable row level security;
revoke all on public.publication_requests from anon,authenticated;
grant select on public.publication_requests to authenticated;
grant all on public.publication_requests to service_role;
grant select on public.publication_requests to anon;
create policy read_allowed on public.publication_requests for select to anon,authenticated using (dao_private.staff() or (dao_private.publication(publication_id)));
alter table public.publication_recipients enable row level security;
revoke all on public.publication_recipients from anon,authenticated;
grant select on public.publication_recipients to authenticated;
grant all on public.publication_recipients to service_role;
create policy read_allowed on public.publication_recipients for select to authenticated using (dao_private.staff() or (dao_private.pro(contractor_id) or exists(select 1 from public.publications p where p.id=publication_id and dao_private.owner(p.project_id))));
alter table public.ai_runs enable row level security;
revoke all on public.ai_runs from anon,authenticated;
grant select on public.ai_runs to authenticated;
grant all on public.ai_runs to service_role;
create policy read_allowed on public.ai_runs for select to authenticated using (dao_private.staff() or (dao_private.owner(project_id)));
alter table public.ai_proposals enable row level security;
revoke all on public.ai_proposals from anon,authenticated;
grant select on public.ai_proposals to authenticated;
grant all on public.ai_proposals to service_role;
create policy read_allowed on public.ai_proposals for select to authenticated using (dao_private.staff() or (dao_private.ai_run(run_id)));
alter table public.bids enable row level security;
revoke all on public.bids from anon,authenticated;
grant select on public.bids to authenticated;
grant all on public.bids to service_role;
create policy read_allowed on public.bids for select to authenticated using (dao_private.staff() or (dao_private.bid(id)));
alter table public.bid_versions enable row level security;
revoke all on public.bid_versions from anon,authenticated;
grant select on public.bid_versions to authenticated;
grant all on public.bid_versions to service_role;
create policy read_allowed on public.bid_versions for select to authenticated using (dao_private.staff() or (dao_private.bid_version(id)));
alter table public.bid_items enable row level security;
revoke all on public.bid_items from anon,authenticated;
grant select on public.bid_items to authenticated;
grant all on public.bid_items to service_role;
create policy read_allowed on public.bid_items for select to authenticated using (dao_private.staff() or (dao_private.bid_version(bid_version_id)));
alter table public.bid_groups enable row level security;
revoke all on public.bid_groups from anon,authenticated;
grant select on public.bid_groups to authenticated;
grant all on public.bid_groups to service_role;
create policy read_allowed on public.bid_groups for select to authenticated using (dao_private.staff() or (dao_private.bid_version(bid_version_id)));
alter table public.bid_group_items enable row level security;
revoke all on public.bid_group_items from anon,authenticated;
grant select on public.bid_group_items to authenticated;
grant all on public.bid_group_items to service_role;
create policy read_allowed on public.bid_group_items for select to authenticated using (dao_private.staff() or (dao_private.bid_version(bid_version_id)));
alter table public.awards enable row level security;
revoke all on public.awards from anon,authenticated;
grant select on public.awards to authenticated;
grant all on public.awards to service_role;
create policy read_allowed on public.awards for select to authenticated using (dao_private.staff() or (dao_private.owner(project_id) or dao_private.pro(contractor_id)));
alter table public.award_items enable row level security;
revoke all on public.award_items from anon,authenticated;
grant select on public.award_items to authenticated;
grant all on public.award_items to service_role;
create policy read_allowed on public.award_items for select to authenticated using (dao_private.staff() or (dao_private.award(award_id)));
alter table public.contracts enable row level security;
revoke all on public.contracts from anon,authenticated;
grant select on public.contracts to authenticated;
grant all on public.contracts to service_role;
create policy read_allowed on public.contracts for select to authenticated using (dao_private.staff() or (dao_private.contract(id) or dao_private.owner(project_id)));
alter table public.contract_versions enable row level security;
revoke all on public.contract_versions from anon,authenticated;
grant select on public.contract_versions to authenticated;
grant all on public.contract_versions to service_role;
create policy read_allowed on public.contract_versions for select to authenticated using (dao_private.staff() or (dao_private.contract(contract_id)));
alter table public.contract_parties enable row level security;
revoke all on public.contract_parties from anon,authenticated;
grant select on public.contract_parties to authenticated;
grant all on public.contract_parties to service_role;
create policy read_allowed on public.contract_parties for select to authenticated using (dao_private.staff() or (dao_private.contract(contract_id)));
alter table public.conversations enable row level security;
revoke all on public.conversations from anon,authenticated;
grant select on public.conversations to authenticated;
grant all on public.conversations to service_role;
create policy read_allowed on public.conversations for select to authenticated using ((dao_private.conversation(id)));
alter table public.conversation_participants enable row level security;
revoke all on public.conversation_participants from anon,authenticated;
grant select on public.conversation_participants to authenticated;
grant all on public.conversation_participants to service_role;
create policy read_allowed on public.conversation_participants for select to authenticated using ((dao_private.conversation(conversation_id)));
alter table public.messages enable row level security;
revoke all on public.messages from anon,authenticated;
grant select on public.messages to authenticated;
grant all on public.messages to service_role;
create policy read_allowed on public.messages for select to authenticated using ((dao_private.conversation(conversation_id)));
alter table public.documents enable row level security;
revoke all on public.documents from anon,authenticated;
grant select on public.documents to authenticated;
grant all on public.documents to service_role;
create policy read_allowed on public.documents for select to authenticated using (dao_private.staff() or (owner_id=auth.uid() or (status='approved' and exists(select 1 from public.document_grants g where g.document_id=documents.id and g.user_id=auth.uid() and g.revoked_at is null))));
alter table public.document_grants enable row level security;
revoke all on public.document_grants from anon,authenticated;
grant select on public.document_grants to authenticated;
grant all on public.document_grants to service_role;
create policy read_allowed on public.document_grants for select to authenticated using (dao_private.staff() or (user_id=auth.uid()));
alter table public.notifications enable row level security;
revoke all on public.notifications from anon,authenticated;
grant select on public.notifications to authenticated;
grant all on public.notifications to service_role;
create policy read_allowed on public.notifications for select to authenticated using ((user_id=auth.uid()));
alter table public.audit_events enable row level security;
revoke all on public.audit_events from anon,authenticated;
grant select on public.audit_events to authenticated;
grant all on public.audit_events to service_role;
create policy read_allowed on public.audit_events for select to authenticated using (dao_private.staff() or (false));
alter table public.command_receipts enable row level security;
revoke all on public.command_receipts from anon,authenticated;
grant select on public.command_receipts to authenticated;
grant all on public.command_receipts to service_role;
create policy read_allowed on public.command_receipts for select to authenticated using ((actor_id=auth.uid()));
alter table public.portfolio_projects enable row level security;
revoke all on public.portfolio_projects from anon,authenticated;
grant select on public.portfolio_projects to authenticated;
grant all on public.portfolio_projects to service_role;
grant select on public.portfolio_projects to anon;
create policy read_allowed on public.portfolio_projects for select to anon,authenticated using (dao_private.staff() or (dao_private.portfolio(id)));
alter table public.portfolio_assets enable row level security;
revoke all on public.portfolio_assets from anon,authenticated;
grant select on public.portfolio_assets to authenticated;
grant all on public.portfolio_assets to service_role;
grant select on public.portfolio_assets to anon;
create policy read_allowed on public.portfolio_assets for select to anon,authenticated using (dao_private.staff() or (dao_private.portfolio(portfolio_project_id) and (status='approved' or dao_private.pro(contractor_id))));
alter table public.bid_documents enable row level security;
revoke all on public.bid_documents from anon,authenticated;
grant select on public.bid_documents to authenticated;
grant all on public.bid_documents to service_role;
create policy read_allowed on public.bid_documents for select to authenticated using (dao_private.staff() or (dao_private.bid_version(bid_version_id) and (status='approved' or dao_private.pro(contractor_id))));
commit;
