'use client';
import {Suspense,useEffect,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import {supabaseBrowser} from '../../../../../lib/supabase-browser';
import {Button,Card} from '../../../../../components/ui';
function NewPublication(){const params=useSearchParams();const router=useRouter();const projectId=params.get('project_id')||'';const [rows,setRows]=useState<any[]>([]);const [contractors,setContractors]=useState<any[]>([]);const [visibility,setVisibility]=useState('public');const [selected,setSelected]=useState<string[]>([]);const [recipients,setRecipients]=useState<string[]>([]);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!projectId)return;void(async()=>{const s=supabaseBrowser();const {data}=await s.from('project_requests').select('id').eq('project_id',projectId).eq('status','open');setRows(data??[]);setSelected((data??[]).map((x:any)=>x.id));const {data:cs}=await s.from('contractor_profiles').select('id,public_name,trade_id').eq('verification_status','verified').order('public_name');setContractors(cs??[])})()},[projectId]);
 async function submit(){setSaving(true);const {data}=await supabaseBrowser().auth.getSession();if(!data.session){setError('Session expirée.');return}const r=await fetch('/api/publications',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({project_id:projectId,visibility,request_ids:selected,contractor_ids:contractors.filter((x:any)=>recipients.includes(x.id)).map((x:any)=>x.id)})});const b=await r.json();if(!r.ok){setError(b.error||'Publication refusée.');setSaving(false);return}router.push('/app/dao/review')}
 return <section className="mx-auto max-w-2xl space-y-6"><div><p className="text-sm font-semibold text-teal">Publication DAO</p><h1 className="mt-1 text-3xl font-bold">Choisir les lots et la visibilité</h1></div><Card><label className="block text-sm font-semibold">Visibilité<select className="mt-2 w-full rounded-xl border p-3" value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">Public</option><option value="targeted">Ciblée</option><option value="invite_only">Sur invitation</option></select></label><div className="mt-5 space-y-2"><p className="text-sm font-semibold">Lots inclus</p>{rows.map((x:any)=><label key={x.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,x.id]:v.filter(id=>id!==x.id))}/>Lot de travaux</label>)}</div>{visibility!=='public'&&<div className="mt-4 space-y-2"><p className="text-sm font-semibold">Destinataires</p>{contractors.map((x:any)=><label key={x.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={recipients.includes(x.id)} onChange={e=>setRecipients(v=>e.target.checked?[...v,x.id]:v.filter(id=>id!==x.id))}/>{x.public_name||'Professionnel vérifié'}</label>)}</div>}{error&&<p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}<Button className="mt-6" disabled={saving||selected.length===0||(visibility!=='public'&&recipients.length===0)} onClick={()=>void submit()}>{saving?'Publication…':'Publier le DAO'}</Button></Card></section>}

export default function PublicationPage(){return <Suspense fallback={<p>Chargement…</p>}><NewPublication/></Suspense>}
