import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
export async function backofficeCases(db,check){
 await db.exec('alter table auth.users add column if not exists email text;');
 const users={};const insert=async(table,input)=>{const keys=Object.keys(input);return (await db.query(`insert into public.${table}(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')}) returning *`,Object.values(input))).rows[0];};
 for(const name of ['client','pro','reviewer','other','admin','admin2']){const id=randomUUID();users[name]=id;await db.query('insert into auth.users(id,email) values($1,$2)',[id,name+'-'+id+'@example.invalid']);await insert('profiles',{user_id:id,display_name:'BO '+name});await insert('user_roles',{user_id:id,role:name.startsWith('admin')?'dao_admin':['reviewer','other'].includes(name)?'dao_reviewer':name==='pro'?'contractor':'client'});}
 const cp=await insert('contractor_profiles',{user_id:users.pro,business_name:'BO pro',verification_status:'verified'});
 const gov=(await db.query('select id from public.governorates limit 1')).rows[0].id,trade=(await db.query('select id from public.trades where active limit 1')).rows[0].id;
 async function as(name,fn){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[users[name]]);await db.exec('set role authenticated');try{return await fn();}finally{await db.exec("reset role;select set_config('request.jwt.claim.sub','',false)");}}
 const rpc=(name,command,args)=>as(name,async()=>(await db.query(`select to_jsonb(public.${command}(${args.map((_,i)=>'$'+(i+1)).join(',')})) as result`,args)).rows[0].result);
 const cmd=(name,action,input,key=randomUUID())=>rpc(name,'backoffice_command',[action,input,key]);
 const deny=(fn,code)=>assert.rejects(fn,e=>e.code===code);
 async function fixture(){const p=await insert('projects',{client_id:users.client});const v=await insert('project_versions',{project_id:p.id,version_no:1,title:'Original',description:'Original scope',governorate_id:gov});const lots=[];for(let i=0;i<2;i++){const r=await insert('project_requests',{project_id:p.id});const rv=await insert('project_request_versions',{project_id:p.id,request_id:r.id,version_no:1,title:'Lot '+i,scope:'Original lot '+i,trade_id:trade});await insert('project_version_requests',{project_id:p.id,project_version_id:v.id,request_version_id:rv.id});lots.push({...rv,sub_lots:[]});}await rpc('client','submit_project_for_review',[p.id]);return {p,v,lots};}
 const f=await fixture();
 await check('BO client submission commits one durable notice and resets assignment',async()=>{const rows=(await db.query('select kind from public.notification_outbox where project_id=$1',[f.p.id])).rows;assert.equal(rows.length,1);assert.equal(rows[0].kind,'review_submitted');assert.equal((await db.query('select reviewer_id from public.review_assignments where project_id=$1',[f.p.id])).rows[0].reviewer_id,null);});
 const claimKey=randomUUID();
 await check('BO claim is idempotent; a second reviewer cannot claim or decide',async()=>{const input={project_id:f.p.id};const first=await cmd('reviewer','claim',input,claimKey);assert.equal(first.status,'dao_review');assert.deepEqual(await cmd('reviewer','claim',input,claimKey),first);await deny(()=>cmd('other','claim',input),'42501');await deny(()=>rpc('other','review_project',[f.p.id,true,null]),'42501');assert.equal((await db.query("select count(*)::int n from public.audit_events where action='review_claimed' and entity_id=$1",[f.p.id])).rows[0].n,1);});
 await check('BO public/dual-role accounts cannot access staff commands or role administration',async()=>{await insert('user_roles',{user_id:users.pro,role:'client'});await deny(()=>cmd('pro','claim',{project_id:f.p.id}),'42501');await deny(()=>cmd('reviewer','role',{user_id:users.pro,role:'dao_admin',enabled:true}),'42501');await deny(()=>rpc('reviewer','backoffice_read',['users',{}]),'42501');await as('reviewer',()=>deny(()=>db.query("update public.user_roles set role='dao_admin' where user_id=$1",[users.reviewer]),'42501'));});
 let revised;
 await check('BO staff revisions preserve original snapshots, stable sub-lot identities and assignment',async()=>{const input={...f.v,title:'Staff title',description:'Staff scope',lots:f.lots.map((l,i)=>({...l,scope:i===0?'Revised lot':l.scope,sub_lots:i===0?[{title:'Technique A',scope:'Scope A',budget_millimes:1001},{title:'Technique B',scope:'Scope B',budget_millimes:null}]:[]}))};revised=await cmd('reviewer','save_review',{project_id:f.p.id,expected_version_id:f.v.id,data:input});assert.equal(revised.version_no,2);assert.equal(revised.status,'dao_review');assert.equal((await db.query('select title,description from public.project_versions where id=$1',[f.v.id])).rows[0].title,'Original');assert.equal((await db.query('select scope from public.project_request_versions where id=$1',[f.lots[0].id])).rows[0].scope,'Original lot 0');assert.equal((await db.query('select reviewer_id from public.review_assignments where project_id=$1',[f.p.id])).rows[0].reviewer_id,users.reviewer);await deny(()=>cmd('reviewer','save_review',{project_id:f.p.id,expected_version_id:f.v.id,data:input}),'23514');await deny(()=>db.query("update public.project_versions set title='corrupted' where id=$1",[f.v.id]),'23514');});
 await check('BO submitted sub-lot snapshots and links are immutable even privileged',async()=>{const sub=(await db.query('select * from public.request_sub_lot_versions where project_id=$1 limit 1',[f.p.id])).rows[0];await deny(()=>db.query("update public.request_sub_lot_versions set scope='corrupted' where id=$1",[sub.id]),'23514');await deny(()=>insert('request_sub_lot_versions',{sub_lot_id:sub.sub_lot_id,request_id:sub.request_id,project_id:sub.project_id,request_version_id:sub.request_version_id,ordinal:2,title:'late',scope:'late'}),'23514');});
 await check('BO Option A approves internal revision directly and publishes technical snapshots',async()=>{assert.equal((await rpc('reviewer','review_project',[f.p.id,true,null])).status,'approved');f.pub=await rpc('reviewer','publish_project',[f.p.id,'public',f.lots.map(l=>l.request_id),null,null]);f.pr=(await db.query('select * from public.publication_requests where publication_id=$1 order by safe_title',[f.pub.id])).rows;assert.equal(f.pr[0].technical_scope.length,2);await deny(()=>rpc('other','publish_project',[f.p.id,'public',f.lots.map(l=>l.request_id),null,null]),'42501');await deny(()=>rpc('reviewer','publish_project',[f.p.id,'public',[f.lots[0].request_id],null,null]),'23505');});
 const offer=await rpc('pro','create_bid_draft',[f.pub.id]);const item=await rpc('pro','upsert_bid_item',[f.pub.id,offer.id,f.pr[0].id,1001,2,'Original offer',null]);await rpc('pro','submit_bid_version',[offer.id]);const preWithdrawalDraft=await rpc('pro','create_bid_draft',[f.pub.id]);await rpc('pro','upsert_bid_item',[f.pub.id,preWithdrawalDraft.id,f.pr[0].id,1002,3,'Unsubmitted',null]);
 await check('BO an unassigned reviewer cannot assist awards; assigned staff actor is audited',async()=>{await deny(()=>rpc('other','award_bid_item_atomic',[randomUUID(),item.id]),'42501');await deny(()=>cmd('reviewer','assisted_award',{bid_item_id:item.id}),'22023');const key=randomUUID();f.award=await cmd('reviewer','assisted_award',{bid_item_id:item.id,reason:'Client request'},key);assert.deepEqual(await cmd('reviewer','assisted_award',{bid_item_id:item.id,reason:'Client request'},key),f.award);const audit=(await db.query("select actor_id,metadata from public.audit_events where action='award_confirmed' and entity_id=$1",[f.p.id])).rows[0];assert.equal(audit.actor_id,users.reviewer);assert.equal(audit.metadata.acting_for_client,true);assert.equal(audit.metadata.client_id,users.client);});
 await check('BO withdrawal requires cancellation of active award and a valid reason',async()=>{await deny(()=>cmd('reviewer','withdraw_publication_lot',{publication_request_id:f.pr[0].id,reason:'correction'}),'23514');await rpc('reviewer','cancel_award_item_atomic',[randomUUID(),f.award.award_item_id,'award_error','Correct before republishing']);await deny(()=>cmd('reviewer','withdraw_publication_lot',{publication_request_id:f.pr[0].id,reason:'other'}),'23514');});
 await check('BO withdrawal blocks new lines, old draft submission and old awards without changing submitted contents',async()=>{const before=(await db.query('select * from public.bid_items where id=$1',[item.id])).rows[0];const key=randomUUID(),input={publication_request_id:f.pr[0].id,reason:'correction'};await cmd('reviewer','withdraw_publication_lot',input,key);await cmd('reviewer','withdraw_publication_lot',input,key);assert.deepEqual((await db.query('select * from public.bid_items where id=$1',[item.id])).rows[0],before);await deny(()=>rpc('pro','upsert_bid_item',[f.pub.id,preWithdrawalDraft.id,f.pr[0].id,2,1,'late',null]),'42501');await deny(()=>rpc('pro','submit_bid_version',[preWithdrawalDraft.id]),'42501');await deny(()=>rpc('reviewer','award_bid_item_atomic',[randomUUID(),item.id]),'23514');const availability=await rpc('pro','publication_lot_availability',[f.pub.id]);assert.equal(availability.find(l=>l.publication_request_id===f.pr[0].id).status,'withdrawn');assert.equal(availability.find(l=>l.publication_request_id===f.pr[1].id).accepts_offers,true);assert.equal((await db.query('select status from public.publications where id=$1',[f.pub.id])).rows[0].status,'published');assert.equal((await db.query("select count(*)::int n from public.notification_outbox where project_id=$1 and kind='lot_withdrawn_professional'",[f.p.id])).rows[0].n,1);});
 await check('BO withdrawal of final lot closes publication; historical bidder retains read access',async()=>{await cmd('reviewer','withdraw_publication_lot',{publication_request_id:f.pr[1].id,reason:'postponed'});assert.equal((await db.query('select status from public.publications where id=$1',[f.pub.id])).rows[0].status,'closed');await as('pro',async()=>assert.equal((await db.query('select id from public.publications where id=$1',[f.pub.id])).rows.length,1));await deny(()=>db.query("update public.publications set status='published',closed_at=null where id=$1",[f.pub.id]),'23514');});
 await check('BO correction requires new approval; republication has a new identity and stable sub-lot IDs',async()=>{const read=(await rpc('reviewer','backoffice_read',['project',{project_id:f.p.id}])).rows;const subIds=read.lots.flatMap(l=>l.sub_lots.map(s=>s.id));const data={...read.version,lots:read.lots.map(l=>({...l,scope:l.scope+' corrected'}))};const next=await cmd('reviewer','save_review',{project_id:f.p.id,expected_version_id:revised.id,data});await deny(()=>rpc('reviewer','publish_project',[f.p.id,'public',[f.lots[0].request_id],null,null]),'23514');await rpc('reviewer','review_project',[f.p.id,true,null]);const pub=await rpc('reviewer','publish_project',[f.p.id,'public',[f.lots[0].request_id],null,null]);assert.notEqual(pub.id,f.pub.id);const nextRead=(await rpc('reviewer','backoffice_read',['project',{project_id:f.p.id}])).rows;assert.deepEqual(nextRead.lots.flatMap(l=>l.sub_lots.map(s=>s.id)),subIds);assert.equal(next.status,'dao_review');});
 await check('BO admin reassigns with reason; old reviewer loses mutation permission immediately',async()=>{const g=await fixture();await cmd('reviewer','claim',{project_id:g.p.id});await deny(()=>cmd('admin','reassign',{project_id:g.p.id,user_id:users.other}),'42501');await cmd('admin','reassign',{project_id:g.p.id,user_id:users.other,reason:'Workload'});await deny(()=>rpc('reviewer','review_project',[g.p.id,true,null]),'42501');assert.equal((await rpc('other','review_project',[g.p.id,true,null])).status,'approved');});
 await check('BO professional suspension cannot be bypassed via reviewer rejection and verification',async()=>{await cmd('admin','professional',{contractor_id:cp.id,decision:'suspend',reason:'Review'});await deny(()=>cmd('reviewer','professional',{contractor_id:cp.id,decision:'reject',reason:'Bypass'}),'42501');await deny(()=>cmd('reviewer','professional',{contractor_id:cp.id,decision:'verify'}),'42501');await deny(()=>rpc('pro','create_bid_draft',[f.pub.id]),'42501');await cmd('admin','professional',{contractor_id:cp.id,decision:'reactivate'});assert.equal((await db.query('select verification_status from public.contractor_profiles where id=$1',[cp.id])).rows[0].verification_status,'pending');await cmd('reviewer','professional',{contractor_id:cp.id,decision:'verify'});await deny(()=>cmd('reviewer','professional',{contractor_id:cp.id,decision:'approve_identity'}),'42501');});
 await check('BO suspension takes effect on existing JWT reads/definer commands without deleting history',async()=>{await cmd('admin','account',{user_id:users.client,status:'suspended',reason:'Administrative hold'});await as('client',async()=>assert.equal((await db.query('select id from public.projects where id=$1',[f.p.id])).rows.length,0));await deny(()=>rpc('client','project_review_history',[f.p.id]),'42501');await as('client',()=>deny(()=>db.query("select public.create_project_draft('other'::text,null::numeric,null::date,null::bigint,$1::uuid,null::uuid,null::uuid)",[gov]),'42501'));await cmd('admin','account',{user_id:users.client,status:'active'});const history=await rpc('client','project_review_history',[f.p.id]);assert.ok(history.versions.length>=3);assert.ok(history.events.every(e=>e.actor_name));});
 await check('BO the last active Admin invariant also protects privileged direct writes',async()=>{const others=(await db.query("select user_id from public.user_roles where role='dao_admin' and user_id not in($1,$2)",[users.admin,users.admin2])).rows;try{for(const a of others)await db.query("insert into public.account_states(user_id,status) values($1,'suspended') on conflict(user_id) do update set status='suspended'",[a.user_id]);await cmd('admin','role',{user_id:users.admin2,role:'dao_admin',enabled:false});await deny(()=>cmd('admin','role',{user_id:users.admin,role:'dao_admin',enabled:false}),'23514');await deny(()=>db.query("insert into public.account_states(user_id,status) values($1,'suspended') on conflict(user_id) do update set status='suspended'",[users.admin]),'23514');}finally{for(const a of others)await db.query("update public.account_states set status='active' where user_id=$1",[a.user_id]);}});
 await check('BO history scope, directory boundaries and append-only audit',async()=>{const own=(await rpc('reviewer','backoffice_read',['history',{project_id:f.p.id}])).rows;assert.ok(own.length>0);assert.equal((await rpc('other','backoffice_read',['history',{project_id:f.p.id}])).rows.length,0);await deny(()=>rpc('pro','backoffice_read',['clients',{}]),'42501');assert.ok((await rpc('admin','backoffice_read',['professionals',{q:'BO pro'}])).rows.length===1);assert.ok((await rpc('admin','backoffice_read',['clients',{q:'BO client'}])).rows.length===1);assert.ok((await rpc('admin','backoffice_read',['staff',{}])).rows.length>=2);assert.ok((await rpc('admin','backoffice_read',['users',{q:'BO client'}])).rows.length===1);await deny(()=>db.query('delete from public.audit_events where id=$1',[own[0].id]),'23514');});
 await check('BO outbox is private, provider failure retains business success and retries are leased/idempotent',async()=>{await as('client',()=>deny(()=>db.query('select * from public.notification_outbox'),'42501'));await as('admin',()=>deny(()=>db.query('select public.claim_notification_outbox(10)'),'42501'));const claimed=(await db.query('select * from public.claim_notification_outbox(50)')).rows;assert.ok(claimed.length>0);const notice=claimed[0];assert.equal(notice.attempts,1);const msg={to:notice.delivery_email,subject:'same'};const prepared=(await db.query('select public.prepare_notification_delivery($1,$2,$3) message',[notice.id,notice.lease_token,msg])).rows[0].message;assert.deepEqual(prepared,msg);assert.deepEqual((await db.query('select public.prepare_notification_delivery($1,$2,$3) message',[notice.id,notice.lease_token,{subject:'different'}])).rows[0].message,msg);assert.equal((await db.query('select public.complete_notification_outbox($1,$2,false,$3) done',[notice.id,notice.lease_token,'RESEND_HTTP_503'])).rows[0].done,true);assert.equal((await db.query('select public.complete_notification_outbox($1,$2,true,null) done',[notice.id,notice.lease_token])).rows[0].done,false);const pending=(await db.query('select status,error_code,attempts from public.notification_outbox where id=$1',[notice.id])).rows[0];assert.equal(pending.status,'pending');assert.equal(pending.attempts,1);assert.ok((await db.query('select count(*)::int n from public.project_versions where project_id=$1',[f.p.id])).rows[0].n>=3);});
}
