import test from 'node:test'; import assert from 'node:assert/strict';
import { AwardService } from '../src/services/AwardService.js';
import { BidService } from '../src/services/BidService.js';
import { DocumentService } from '../src/services/DocumentService.js';
import { requireActor } from '../src/server/auth.js';
const fake=(table,rows={})=>({rpc:(name,input)=>({data:name==='submit_bid_version'?{...input,status:'submitted'}:{...input,award_item_id:'1'},error:null}),from(t){assert.equal(t,table);return {insert:(x)=>({select:()=>({single:async()=>({data:{...x,id:'1'},error:null})})}),update:()=>({eq:()=>({eq:()=>({select:()=>({single:async()=>({data:{id:'v',status:'submitted'},error:null})})})})}),select:()=>({eq:()=>({single:async()=>({data:rows,error:null})})})}}});
test('BidService submits a draft idempotently',async()=>{const s=new BidService(fake('bid_versions'));const x=await s.submit('v');assert.equal(x.status,'submitted')});
test('BidService creates drafts and lines through secured RPC commands',async()=>{const calls:any[]=[];const s=new BidService({rpc:async(name:string,input:any)=>{calls.push({name,input});return {data:{id:'v'},error:null}}});await s.createDraft({publication_id:'pub'});await s.addItem({publication_id:'pub',version_id:'v',publication_request_id:'lot',price_millimes:1200000,duration_days:10,inclusions:'Pose'});assert.deepEqual(calls,[{name:'create_bid_draft',input:{p_publication_id:'pub'}},{name:'upsert_bid_item',input:{p_publication_id:'pub',p_version_id:'v',p_publication_request_id:'lot',p_price_millimes:1200000,p_duration_days:10,p_inclusions:'Pose',p_exclusions:null}}])});
test('AwardService delegates uniqueness to DB',async()=>{const s=new AwardService(fake('award_items'));assert.equal((await s.award({request_id:'r',idempotency_key:'idem-1234'})).p_request_id,'r')});
test('DocumentService refuses unapproved documents',async()=>{const s=new DocumentService(fake('bid_documents',{status:'quarantined',object_path:'x'}),{});await assert.rejects(()=>s.signedDownload('d'),/not approved/)});
test('server actions require an authenticated actor',()=>{assert.throws(()=>requireActor(null),/Authentication required/)});
test('actor identity is required, never accepted from browser payload',()=>{const actor=requireActor({id:'actor'});assert.equal(actor.id,'actor');assert.notEqual(actor.id,'browser-supplied')});
