import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

test('Backoffice V2 real JWT, isolation and independent transaction races',async t=>{
 const url=process.env.DAO_SUPABASE_URL!;assert.equal(url,'http://127.0.0.1:54321','Disposable local stack required');const key=process.env.DAO_SUPABASE_PUBLISHABLE_KEY!,secret=process.env.DAO_SUPABASE_SECRET_KEY!;assert.ok(key);assert.ok(secret);
 const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),users:any={};
 async function insert(table:string,input:any){const r=await admin.from(table).insert(input).select('*').single();assert.ifError(r.error);return r.data;}
 async function rpc(db:any,name:string,args:any){const r=await db.rpc(name,args);assert.ifError(r.error);return r.data;}
 const cmd=(name:string,action:string,input:any,k=randomUUID())=>rpc(users[name].db,'backoffice_command',{p_action:action,p_input:input,p_key:k});
 for(const name of ['client','pro','reviewer','other','admin','admin2']){const email=`bo-${name}-${randomUUID()}@example.invalid`,password='BO!'+randomUUID();const auth=await admin.auth.admin.createUser({email,password,email_confirm:true});assert.ifError(auth.error);const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});assert.ifError((await db.auth.signInWithPassword({email,password})).error);users[name]={id:auth.data.user!.id,db};await insert('profiles',{user_id:users[name].id,display_name:'BO '+name});await insert('user_roles',{user_id:users[name].id,role:name.startsWith('admin')?'dao_admin':['reviewer','other'].includes(name)?'dao_reviewer':name==='pro'?'contractor':'client'});}
 const pro=await insert('contractor_profiles',{user_id:users.pro.id,business_name:'BO pro',verification_status:'verified'});const gov=(await admin.from('governorates').select('id').eq('code','E2E_TEST').single()).data!.id,trade=(await admin.from('trades').select('id').eq('code','plumbing').single()).data!.id;
 async function fixture(){const p=await insert('projects',{client_id:users.client.id});const v=await insert('project_versions',{project_id:p.id,version_no:1,title:'BO real '+randomUUID(),description:'Original scope',governorate_id:gov});const lots=[];for(let i=0;i<2;i++){const r=await insert('project_requests',{project_id:p.id});const rv=await insert('project_request_versions',{project_id:p.id,request_id:r.id,version_no:1,title:'Lot '+i,scope:'Original',trade_id:trade});await insert('project_version_requests',{project_id:p.id,project_version_id:v.id,request_version_id:rv.id});lots.push({...rv,sub_lots:[]});}await rpc(users.client.db,'submit_project_for_review',{p_project_id:p.id});return {p,v,lots};}
 async function publish(){const f:any=await fixture();await cmd('reviewer','claim',{project_id:f.p.id});await rpc(users.reviewer.db,'review_project',{p_project_id:f.p.id,p_approve:true,p_comment:null});f.pub=await rpc(users.reviewer.db,'publish_project',{p_project_id:f.p.id,p_visibility:'public',p_request_ids:f.lots.map((l:any)=>l.request_id)});f.pr=(await admin.from('publication_requests').select('*').eq('publication_id',f.pub.id).order('safe_title')).data!;f.draft=await rpc(users.pro.db,'create_bid_draft',{p_publication_id:f.pub.id});f.item=await rpc(users.pro.db,'upsert_bid_item',{p_publication_id:f.pub.id,p_version_id:f.draft.id,p_publication_request_id:f.pr[0].id,p_price_millimes:1001,p_duration_days:2,p_inclusions:'Original immutable offer',p_exclusions:null});return f;}
 await t.test('two reviewers claiming concurrently produce exactly one assignment/audit/email',async()=>{const f=await fixture();const results=await Promise.all(['reviewer','other'].map(name=>users[name].db.rpc('backoffice_command',{p_action:'claim',p_input:{project_id:f.p.id},p_key:randomUUID()})));assert.equal(results.filter(r=>!r.error).length,1);assert.equal(results.find(r=>r.error)!.error.code,'42501');const assignment=(await admin.from('review_assignments').select('*').eq('project_id',f.p.id).single()).data!;assert.ok([users.reviewer.id,users.other.id].includes(assignment.reviewer_id));assert.equal((await admin.from('audit_events').select('id').eq('entity_id',f.p.id).eq('action','review_claimed')).data!.length,1);assert.equal((await admin.from('notification_outbox').select('id').eq('project_id',f.p.id).eq('kind','review_claimed')).data!.length,1);});
 await t.test('staff versions preserve submitted content; client sees names and exact technical history',async()=>{const f=await fixture();await cmd('reviewer','claim',{project_id:f.p.id});const revised=await cmd('reviewer','save_review',{project_id:f.p.id,expected_version_id:f.v.id,data:{...f.v,title:'Edited',lots:f.lots.map(l=>({...l,sub_lots:[{title:'Child',scope:'Child exact scope',budget_millimes:1001}]}))}});assert.equal(revised.version_no,2);assert.equal((await admin.from('project_versions').select('title').eq('id',f.v.id).single()).data!.title,f.v.title);assert.ok((await admin.from('project_versions').update({title:'bad'}).eq('id',f.v.id)).error);assert.equal((await users.other.db.rpc('review_project',{p_project_id:f.p.id,p_approve:true})).error!.code,'42501');const history=await rpc(users.client.db,'project_review_history',{p_project_id:f.p.id});assert.equal(history.versions[0].author_name,'BO reviewer');assert.equal(history.versions[0].lots[0].sub_lots[0].scope,'Child exact scope');assert.ok((await users.pro.db.rpc('project_review_history',{p_project_id:f.p.id})).error);});
 await t.test('withdrawal racing submission commits one consistent outcome and retains old draft/content',async()=>{const f=await publish();const [withdraw,submit]=await Promise.all([users.reviewer.db.rpc('backoffice_command',{p_action:'withdraw_publication_lot',p_input:{publication_request_id:f.pr[0].id,reason:'correction'},p_key:randomUUID()}),users.pro.db.rpc('submit_bid_version',{p_version_id:f.draft.id})]);assert.ifError(withdraw.error);if(submit.error)assert.equal(submit.error.code,'42501');const bv=(await admin.from('bid_versions').select('*').eq('id',f.draft.id).single()).data!;assert.equal(bv.status,submit.error?'draft':'submitted');assert.equal((await admin.from('bid_items').select('inclusions').eq('id',f.item.id).single()).data!.inclusions,'Original immutable offer');const upsert=await users.pro.db.rpc('upsert_bid_item',{p_publication_id:f.pub.id,p_version_id:f.draft.id,p_publication_request_id:f.pr[0].id,p_price_millimes:1,p_duration_days:1,p_inclusions:'Late'});assert.ok(upsert.error);const availability=await rpc(users.pro.db,'publication_lot_availability',{p_publication_id:f.pub.id});assert.equal(availability.filter((l:any)=>l.accepts_offers).length,1);});
 await t.test('withdrawal racing award is mutually exclusive and leaves no partial business history',async()=>{const f=await publish();await rpc(users.pro.db,'submit_bid_version',{p_version_id:f.draft.id});const [withdraw,award]=await Promise.all([users.reviewer.db.rpc('backoffice_command',{p_action:'withdraw_publication_lot',p_input:{publication_request_id:f.pr[0].id,reason:'publication_error'},p_key:randomUUID()}),users.reviewer.db.rpc('award_bid_item_atomic',{p_idempotency_key:randomUUID(),p_bid_item_id:f.item.id})]);assert.equal([withdraw,award].filter(r=>!r.error).length,1);const withdrawals=(await admin.from('publication_lot_withdrawals').select('id').eq('publication_request_id',f.pr[0].id)).data!;const awards=(await admin.from('award_items').select('id').eq('request_id',f.item.request_id).eq('active',true)).data!;assert.equal(withdrawals.length+awards.length,1);if(withdraw.error)assert.match(withdraw.error.message,/Annuler/);else assert.equal(award.error!.code,'23514');});
 await t.test('last active admin cannot be removed by two concurrent role commands',async()=>{const results=await Promise.all([['admin','admin2'],['admin2','admin']].map(([actor,target])=>users[actor].db.rpc('backoffice_command',{p_action:'role',p_input:{user_id:users[target].id,role:'dao_admin',enabled:false},p_key:randomUUID()})));assert.equal(results.filter(r=>!r.error).length,1);const active=(await admin.from('user_roles').select('user_id').eq('role','dao_admin')).data!;assert.equal(active.length,1);const remaining=active[0].user_id===users.admin.id?'admin':'admin2';assert.equal((await users[remaining].db.rpc('backoffice_command',{p_action:'role',p_input:{user_id:users[remaining].id,role:'dao_admin',enabled:false},p_key:randomUUID()})).error!.code,'23514');users.activeAdmin=users[remaining];});
 await t.test('suspension blocks existing JWT and dual-role marketplace actions but keeps history',async()=>{const f=await fixture();await rpc(users.activeAdmin.db,'backoffice_command',{p_action:'account',p_input:{user_id:users.client.id,status:'suspended',reason:'Hold'},p_key:randomUUID()});assert.equal((await users.client.db.from('projects').select('id').eq('id',f.p.id)).data!.length,0);assert.ok((await users.client.db.rpc('submit_project_for_review',{p_project_id:f.p.id})).error);await rpc(users.activeAdmin.db,'backoffice_command',{p_action:'account',p_input:{user_id:users.client.id,status:'active'},p_key:randomUUID()});assert.equal((await users.client.db.from('projects').select('id').eq('id',f.p.id)).data!.length,1);await insert('user_roles',{user_id:users.pro.id,role:'client'});assert.ok((await users.pro.db.rpc('backoffice_read',{p_view:'users'})).error);await rpc(users.activeAdmin.db,'backoffice_command',{p_action:'professional',p_input:{contractor_id:pro.id,decision:'suspend',reason:'Review'},p_key:randomUUID()});const rejected=await users.reviewer.db.rpc('backoffice_command',{p_action:'professional',p_input:{contractor_id:pro.id,decision:'reject',reason:'Bypass'},p_key:randomUUID()});assert.equal(rejected.error!.code,'42501');});
 await t.test('outbox leases distribute independent workers once and provider errors leave events pending',async()=>{const results=await Promise.all([admin.rpc('claim_notification_outbox',{p_limit:50}),admin.rpc('claim_notification_outbox',{p_limit:50})]);results.forEach(r=>assert.ifError(r.error));const ids=results.flatMap(r=>r.data!.map((row:any)=>row.id));assert.equal(new Set(ids).size,ids.length);assert.ok(ids.length>0);const row=results.find(r=>r.data!.length)!.data![0];assert.equal((await users.reviewer.db.from('notification_outbox').select('*')).error!.code,'42501');assert.ok((await users.activeAdmin.db.rpc('claim_notification_outbox',{p_limit:1})).error);assert.equal(await rpc(admin,'complete_notification_outbox',{p_id:row.id,p_lease:row.lease_token,p_success:false,p_code:'RESEND_HTTP_503'}),true);const pending=(await admin.from('notification_outbox').select('status,attempts').eq('id',row.id).single()).data!;assert.equal(pending.status,'pending');assert.equal(pending.attempts,1);});
});
