import { createClient } from '@supabase/supabase-js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { BidService } from '../../src/services/BidService.js';

test('autonomous Supabase integration', async () => {
  for (const name of ['DAO_SUPABASE_URL','DAO_SUPABASE_PUBLISHABLE_KEY','DAO_SUPABASE_SECRET_KEY']) assert.ok(process.env[name], 'missing '+name);
  const url=process.env.DAO_SUPABASE_URL!, pub=process.env.DAO_SUPABASE_PUBLISHABLE_KEY!, secret=process.env.DAO_SUPABASE_SECRET_KEY!;
  const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
  const suffix=Date.now().toString(36), password='T!Dao-'+suffix+'-x9', actors:any={}, rows:any[]=[];
  const insert=async(table:string,row:any)=>{const r=await admin.from(table).insert(row).select('id').single();assert.ifError(r.error);rows.push({table,id:r.data.id});return r.data.id;};
  try {
    for (const role of ['clientA','clientB','plumberA','plumberB','dual']) {
      const email='dao-'+role+'-'+suffix+'@example.invalid'; const r=await admin.auth.admin.createUser({email,password,email_confirm:true}); assert.ifError(r.error); actors[role]={id:r.data.user!.id,email};
      await insert('profiles',{user_id:actors[role].id,display_name:'DAO '+role}); await insert('user_roles',{user_id:actors[role].id,role:role.startsWith('client')?'client':'contractor'});
    }
    await insert('user_roles',{user_id:actors.dual.id,role:'client'});
    const g=await admin.from('governorates').select('id').limit(1); assert.ifError(g.error); assert.ok(g.data?.[0]);
    const t=await admin.from('trades').select('id').eq('active',true).limit(1); assert.ifError(t.error); assert.ok(t.data?.[0]);
    const gov=g.data![0].id, trade=t.data![0].id;
    for (const role of ['plumberA','plumberB']) actors[role].contractorId=await insert('contractor_profiles',{user_id:actors[role].id,business_name:'DAO '+role,verification_status:'verified',contractor_type:'artisan',public_presentation:'test',public_identity_status:'approved'});
    const project=await insert('projects',{client_id:actors.clientA.id,project_type:'renovation',surface_m2:100});
    const version=await insert('project_versions',{project_id:project,version_no:1,title:'Disposable',description:'test',governorate_id:gov,status:'approved'});
    const projectB=await insert('projects',{client_id:actors.clientA.id,project_type:'renovation',surface_m2:90});
    const versionB=await insert('project_versions',{project_id:projectB,version_no:1,title:'Targeted disposable',description:'test',governorate_id:gov,status:'approved'});
    const projectC=await insert('projects',{client_id:actors.clientA.id,project_type:'renovation',surface_m2:80});
    const versionC=await insert('project_versions',{project_id:projectC,version_no:1,title:'Invite disposable',description:'test',governorate_id:gov,status:'approved'});
    const request=await insert('project_requests',{project_id:project}); const rv=await insert('project_request_versions',{request_id:request,project_id:project,version_no:1,trade_id:trade,title:'Plomberie',scope:'test'});
    const publicPub=await insert('publications',{project_id:project,project_version_id:version,visibility:'public',safe_title:'Public',safe_description:'test',governorate_id:gov,project_type:'renovation',published_at:new Date().toISOString()});
    const targeted=await insert('publications',{project_id:projectB,project_version_id:versionB,visibility:'targeted',safe_title:'Targeted',safe_description:'test',governorate_id:gov,project_type:'renovation',published_at:new Date().toISOString()});
    await insert('publication_recipients',{publication_id:targeted,contractor_id:actors.plumberA.contractorId,source:'targeted'});
    const bid=await insert('bids',{project_id:project,contractor_id:actors.plumberB.contractorId});
    const submitted=await insert('bid_versions',{bid_id:bid,project_id:project,contractor_id:actors.plumberB.contractorId,version_no:1,expires_at:'2099-01-01T00:00:00Z',status:'draft'}); actors.submittedVersion=submitted;
    const item=await insert('bid_items',{bid_version_id:submitted,project_id:project,contractor_id:actors.plumberB.contractorId,request_version_id:rv,request_id:request,price_millimes:1000,duration_days:1,inclusions:'test'});
    const bid2=await insert('bids',{project_id:project,contractor_id:actors.plumberA.contractorId});
    const submitted2=await insert('bid_versions',{bid_id:bid2,project_id:project,contractor_id:actors.plumberA.contractorId,version_no:1,expires_at:'2099-01-01T00:00:00Z',status:'draft'});
    const item2=await insert('bid_items',{bid_version_id:submitted2,project_id:project,contractor_id:actors.plumberA.contractorId,request_version_id:rv,request_id:request,price_millimes:1100,duration_days:1,inclusions:'test'});
    const award=await insert('awards',{project_id:project,contractor_id:actors.plumberB.contractorId});
    const award2=await insert('awards',{project_id:project,contractor_id:actors.plumberA.contractorId});
    const login=async(a:any)=>{const userClient=createClient(url,pub);const r=await userClient.auth.signInWithPassword({email:a.email,password});assert.ifError(r.error);return createClient(url,pub,{global:{headers:{Authorization:'Bearer '+r.data.session!.access_token}}});};
    const client=await login(actors.clientA), a=await login(actors.plumberA), b=await login(actors.plumberB), other=await login(actors.clientB), dual=await login(actors.dual);
    assert.equal((await client.from('bids').select('id').eq('id',bid)).data?.length,0);
    assert.equal((await b.from('bid_versions').select('id').eq('id',submitted)).data?.length,1);
    assert.equal((await a.from('bid_versions').select('id').eq('id',submitted2)).data?.length,1);
    await new BidService(b).submitForActor(submitted,actors.plumberB.id);
    await new BidService(a).submitForActor(submitted2,actors.plumberA.id);
    assert.equal((await client.from('bid_versions').select('id').eq('id',submitted)).data?.length,1);
    assert.equal((await other.from('bid_versions').select('id').eq('id',submitted)).data?.length,0);
    assert.equal((await other.from('publications').select('id').eq('id',publicPub)).data?.length,1);
    assert.equal((await a.from('publications').select('id').eq('id',targeted)).data?.length,1);
    assert.equal((await other.from('publications').select('id').eq('id',targeted)).data?.length,0);
    assert.equal((await dual.from('user_roles').select('role').in('role',['client','contractor'])).data?.length,2);
    const invite=await insert('publications',{project_id:projectC,project_version_id:versionC,visibility:'invite_only',safe_title:'Invite',safe_description:'test',governorate_id:gov,project_type:'renovation',published_at:new Date().toISOString()});
    await insert('publication_recipients',{publication_id:invite,contractor_id:actors.plumberB.contractorId,source:'invitation'});
    assert.equal((await b.from('publications').select('id').eq('id',invite)).data?.length,1);
    assert.equal((await other.from('publications').select('id').eq('id',invite)).data?.length,0);
    const objectPath='bid/'+submitted+'/autonomous-'+suffix+'.pdf';
    const upload=await admin.storage.from('dao-private').createSignedUploadUrl(objectPath); assert.ifError(upload.error); assert.ok(upload.data?.token);
    const put=await createClient(url,pub).storage.from('dao-private').uploadToSignedUrl(objectPath,upload.data!.token,new Blob(['test'],{type:'application/pdf'})); assert.ifError(put.error);
    const doc=await insert('bid_documents',{bid_version_id:submitted,project_id:project,contractor_id:actors.plumberB.contractorId,object_path:objectPath,original_name:'test.pdf',mime_type:'application/pdf',size_bytes:4,status:'approved'});
    assert.equal((await client.from('bid_documents').select('id').eq('id',doc)).data?.length,1);
    assert.equal((await a.from('bid_documents').select('id').eq('id',doc)).data?.length,0);
    const signed=await admin.storage.from('dao-private').createSignedUrl(objectPath,60); assert.ifError(signed.error); assert.ok(signed.data?.signedUrl);
    const key='autonomous-'+suffix, params={p_idempotency_key:key,p_award_id:award,p_project_id:project,p_contractor_id:actors.plumberB.contractorId,p_request_id:request,p_bid_item_id:item,p_agreed_millimes:1000};
    const first=await client.rpc('award_request_atomic',params); assert.ifError(first.error); const replay=await client.rpc('award_request_atomic',params); assert.ifError(replay.error); assert.deepEqual(first.data,replay.data);
    const denied=await other.rpc('award_request_atomic',{...params,p_idempotency_key:key+'-other'}); assert.ok(denied.error);
    const second=await client.rpc('award_request_atomic',{...params,p_idempotency_key:key+'-second',p_award_id:award2,p_contractor_id:actors.plumberA.contractorId,p_bid_item_id:item2});
    assert.ok(second.error); assert.match((second.error?.code||'')+' '+(second.error?.message||''),/23505|one_active_award_per_request/i);
  } finally { for (const r of rows.reverse()) await admin.from(r.table).delete().eq('id',r.id); if (typeof suffix !== 'undefined') await admin.storage.from('dao-private').remove(['bid/'+(actors.submittedVersion||'')+'/autonomous-'+suffix+'.pdf']); for (const role of Object.keys(actors)) if (actors[role].id) await admin.auth.admin.deleteUser(actors[role].id); }
});
