'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {supabaseBrowser} from '../../../../../lib/supabase-browser';
import {Badge,Button,Card} from '../../../../../components/ui';
export default function ProjectReview(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [project,setProject]=useState<any>(); const [version,setVersion]=useState<any>(); const [requests,setRequests]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{void(async()=>{const s=supabaseBrowser();const [p,v,r,rv]=await Promise.all([s.from('projects').select('*').eq('id',id).single(),s.from('project_versions').select('*').eq('project_id',id).order('version_no',{ascending:false}).limit(1),s.from('project_requests').select('id,status').eq('project_id',id).neq('status','withdrawn'),s.from('project_request_versions').select('request_id,title,scope,budget_millimes,version_no').eq('project_id',id).order('version_no',{ascending:false})]);setProject(p.data);setVersion(v.data?.[0]);const latest=new Map<string,any>();(rv.data??[]).forEach((x:any)=>{if(!latest.has(x.request_id))latest.set(x.request_id,x)});setRequests((r.data??[]).map((x:any)=>({...x,...latest.get(x.id)})));setLoading(false)})()},[id]);
 async function submit(){setSaving(true);setError('');const {data}=await supabaseBrowser().auth.getSession();if(!data.session){router.push('/auth/login');return}const res=await fetch('/api/projects/review',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({project_id:id})});const body=await res.json();if(!res.ok){setError(body.error||'Soumission refusée.');setSaving(false);return}router.push(`/app/projects/${id}`)}
 if(loading)return <p>Chargement…</p>; if(!project||!version)return <p role="alert">Projet introuvable.</p>;
 const total=requests.reduce((sum,x)=>sum+Number(x.budget_millimes||0),0);
 return <section className="mx-auto max-w-4xl space-y-6"><div><p className="text-sm font-semibold text-teal">Revue du DAO</p><h1 className="mt-1 text-3xl font-bold">{version.title}</h1><p className="mt-2 text-black/60">{version.description||'Sans description'}</p></div><Card><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-black/45">Type</p><p className="font-semibold">{version.project_type}</p></div><div><p className="text-xs text-black/45">Surface</p><p className="font-semibold">{version.surface_m2??'—'} m²</p></div><div><p className="text-xs text-black/45">Budget lots</p><p className="font-semibold">{(total/1000).toLocaleString('fr-TN')} TND</p></div></div></Card><Card><div className="flex items-center justify-between"><h2 className="font-semibold">Lots inclus</h2><Badge>{requests.length} lot{requests.length>1?'s':''}</Badge></div><div className="mt-4 space-y-3">{requests.map((x:any)=><article key={x.id} className="rounded-xl bg-sand/70 p-4"><div className="flex justify-between gap-3"><h3 className="font-semibold">{x.title}</h3><span className="text-sm">{x.budget_millimes?((Number(x.budget_millimes)/1000).toLocaleString('fr-TN')+' TND'):'Budget non renseigné'}</span></div><p className="mt-2 text-sm text-black/60">{x.scope}</p></article>)}</div></Card>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex flex-wrap gap-3"><Button onClick={()=>void submit()} disabled={saving||requests.length===0}>{saving?'Soumission…':'Soumettre pour revue DAO'}</Button><Button type="button" className="bg-white text-ink" onClick={()=>router.push(`/app/projects/${id}`)}>Retour au projet</Button></div></section>;
}